### ISSUE TITLE
Q: Can this be used from F#, or is it C# specific?

### ISSUE THREAD

**Issue by jay-swyfft** [Sergio0694/ComputeSharp#108]
I imagine that it could be used via F#, but perhaps it translates C# expressions to HLSL, in which case it probably couldn't.

**Comment by Sergio0694** [comment]
That's a good question! 😄
While it is correct that the library generates the HLSL shaders by translating C# at compile time, and so it's not directly usable purely from an F# project, it's definitely possible to just create a small C# project that just contains the shaders and nothing else, and then keep all the actual logic in F#, with anything from allocating buffers to dispatching shaders, that will work just fine. I opened a PR and added a complete sample to showcase how this can be achieved, and I've also added a new paragraph to the readme.

Hope this helps, thanks for the question and for your interest in the library!

**Comment by jay-swyfft** [comment]
Thanks!
