### ISSUE TITLE
Swapchain application sample Exception

### ISSUE THREAD

**Issue by Kaitoukid93** [Sergio0694/ComputeSharp#135]
Hello!
I ran into this problem when select sample from console window, the shader picture appeared for half second and this exception show up, I don't know if my system is enough for this library, I have search around for this exception but nothing help
core i5 4570-gtx960 2gb, windows 11
`System.ComponentModel.Win32Exception: 'Warning or error detected by ID3D12InfoQueue'`

![image](https://user-images.githubusercontent.com/40384831/130372361-5a659540-7c97-4439-8539-d6c4de8f73c3.png)

One more thing want to ask  ( if I can go further ), is it possible to get frame by frame data of shader animation at runtime?
I want to get a bitmap image or RGB pixel data with position (x,y) so I can display to a matrix RGB LED with lowest latency
I have tried RenderTargetBitmap to get bitmap frame bit this method too slow and high CPU usage
Thanks!. Sorry because I'm new to C# wpf programming

**Comment by Sergio0694** [comment]
Hi!
You should see some error messages in the output window when you hit that exception, could you share them here as well? It'd be impossible for me to figure out what's wrong on your device without knowing what the info queue is complaining about 😄
This also makes me think I should update that code to also include some more info in the exception message.

> "is it possible to get frame by frame data of shader animation at runtime?"
Of course! Also note that if you only want to extract each frame individually, then you don't actually need the whole swap chain setup at all, you can just render each frame individually and then copy it wherever you want. Something like:

```csharp
using ReadWriteTexture2D<Rgba32, Float4> texture = Gpu.Default.AllocateReadWriteTexture2D<Rgba32, Float4>(1920, 1080);
using ReadBackTexture2D<Rgba32> buffer = Gpu.Default.AllocateReadBackTexture2D<Rgba32>(1920, 1080);

// For each frame
for (int i = 0; i < 30; i++)
{
    float timestamp = 1 / 30f * i;

    // Run the shader
    Gpu.Default.ForEach(texture, new ColorfulInfinity(timestamp));

    // Copy the rendered frame to a readback texture that can be accessed by the CPU.
    // The rendered texture can only be accessed by the GPU, so we can't read from it.
    texture.CopyTo(buffer);

    // Access buffer.View here and do all your work with the frame data
}
```

Let me know if that helps!
Also even in case this works for you, do please share those error messages so we can get the swap chain working for you too! 🙂

**Comment by Kaitoukid93** [comment]
Thank you so much!, I forgot about output window:
`[D3D12 message #0 for "[46268] NVIDIA GeForce GTX 960" (HW: True, UMA: False)]
[Category]: D3D12_MESSAGE_CATEGORY_RESOURCE_MANIPULATION
[Severity]: D3D12_MESSAGE_SEVERITY_ERROR
[ID]: D3D12_MESSAGE_ID_RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH
[Description]: "ID3D12CommandQueue::ExecuteCommandLists: Using ResourceBarrier on Command List (0x000001A0554C7760:'Unnamed ID3D12GraphicsCommandList Object'): Before state (0x4: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x000001A0551E7190:'Unnamed ID3D12Resource Object') (subresource: 0) specified by transition barrier does not match with the state (0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) specified in the previous call to ResourceBarrier"
[D3D12 message #1 for "[46268] NVIDIA GeForce GTX 960" (HW: True, UMA: False)]
[Category]: D3D12_MESSAGE_CATEGORY_EXECUTION
[Severity]: D3D12_MESSAGE_SEVERITY_ERROR
[ID]: D3D12_MESSAGE_ID_GPU_BASED_VALIDATION_INCOMPATIBLE_RESOURCE_STATE
[Description]: "GPU-BASED VALIDATION: ResourceBarrier, StateBefore invalid, Barrier array index [0], Incompatible resource state: Resource: 0x000001A0551E7190:'Unnamed ID3D12Resource Object', Subresource Index: [0], Resource State: D3D12_RESOURCE_STATE_[COMMON|PRESENT](0x0), Required State Bits: D3D12_RESOURCE_STATE_RENDER_TARGET(0x4), Draw Count [0], Dispatch Count [0], Command List: 0x000001A0554C7760:'Unnamed ID3D12GraphicsCommandList Object', "
'ComputeSharp.SwapChain.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.7\Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.ComponentModel.Win32Exception' in Microsoft.Toolkit.Diagnostics.dll
An exception of type 'System.ComponentModel.Win32Exception' occurred in Microsoft.Toolkit.Diagnostics.dll but was not handled in user code
Warning or error detected by ID3D12InfoQueue`

**Comment by Kaitoukid93** [comment]
> Hi!
> You should see some error messages in the output window when you hit that exception, could you share them here as well? It'd be impossible for me to figure out what's wrong on your device without knowing what the info queue is complaining about 😄
> This also makes me think I should update that code to also include some more info in the exception message.
> 
> > "is it possible to get frame by frame data of shader animation at runtime?"
> > Of course! Also note that if you only want to extract each frame individually, then you don't actually need the whole swap chain setup at all, you can just render each frame individually and then copy it wherever you want. Something like:
> 
> ```cs
> using ReadWriteTexture2D<Rgba32, Float4> texture = Gpu.Default.AllocateReadWriteTexture2D<Rgba32, Float4>(1920, 1080);
> using ReadBackTexture2D<Rgba32> buffer = Gpu.Default.AllocateReadBackTexture2D<Rgba32>(1920, 1080);
> 
> // For each frame
> for (int i = 0; i < 30; i++)
> {
>     float timestamp = 1 / 30f * i;
> 
>     // Run the shader
>     Gpu.Default.ForEach(texture, new ColorfulInfinity(timestamp));
> 
>     // Copy the rendered frame to a readback texture that can be accessed by the CPU.
>     // The rendered texture can only be accessed by the GPU, so we can't read from it.
>     texture.CopyTo(buffer);
> 
>     // Access buffer.View here and do all your work with the frame data
> }
> ```
> 
> Let me know if that helps!
> Also even in case this works for you, do please share those error messages so we can get the swap chain working for you too! 🙂

thanks for this, I will try. I want to ask if it's possible to do this offscreen for example when the application is in system tray(  this code will be executed in background thread) and I only want to copy the pixel data of the shader output only, not entire fullHD screen. I know I can crop the section of shader view but then the application always have to be visible or in full screen mode
![image](https://user-images.githubusercontent.com/40384831/130440571-d4e33332-e1ab-463a-a58b-f2abf6b8f777.png)

**Comment by Sergio0694** [comment]
> "I want to ask if it's possible to do this offscreen for example when the application is in system tray"

@Kaitoukid93 That code I posted does work offscreen, in fact it doesn't render anything to screen at all. Each frame is just rendered to a texture, and then copied back to CPU memory, where you can read the pixels and do anything you need with them. You don't need to have a swapchain being rendered on screen, and you don't have to care about the window/screen resolution either, you can just initialize that texture to whatever size you want and then render to it directly 🙂

**Comment by Kaitoukid93** [comment]
Thanks, I've tried your code and was able to get data as R,G,B inside your console sample application.
After upgrading my application to net5, I moved the exact same code to my application, add ComputeSharp nuget package by  package manager console, ComputeSharp.SourceGenerator did appear as analyzer dependency,no error show up then I hit build
The Build failed and show the error that as I understand, ComputeSharp.SourceGenerator should take care of
` Gpu.Default.ForEach(texture, new ColorfulInfinity(timestamp));`
`
'ColorfulInfinity' does not contain a constructor that takes 1 arguments
`

This error not show up when coding but show up when compiling 
![image](https://user-images.githubusercontent.com/40384831/130672012-ae5ef125-63b3-4496-8a99-3f64cbdb7fd5.png)

**Comment by Sergio0694** [comment]
> "I compile with the lastest build of VS Preview and no more error"

Glad to hear that! 🥳

@Kaitoukid93 just wondering whether I can close this issue now, are you still getting that crash when running the sample?
