### ISSUE TITLE
Why don't use veldrid as backing api?

### ISSUE THREAD

**Issue by Kemsekov** [Sergio0694/ComputeSharp#136]
### Description

Review and remade source code to be backing api independent

### Rationale

`ComputeSharp` uses `dx12` as backing api and I am not so happy about it with my linux laptop. Even if it works under `wine` I still lack some flexability towards available backing api. Why don't do some abstraction towards gpu api by using `veldrid` for example?

### Proposed API

`Veldrid` is a opensource low-level, portable graphics library for .NET.

**Comment by Sergio0694** [comment]
Unfortunately this is not really something I'm planning on doing. ComputeSharp is specifically designed to integrate with DirectX 12 APIs and to leverage many of the features it exposes, and trying to have it support a different backend would take a huge amount of work, that I don't really have time to do right now, not to mention all the research that would be needed. If I was to move to a different backend in the future, it'd probably be Vulkan, leveraging the HLSL to SPIR-V compilation that the DX compiler offers, but even then, it's not really something I'm planning on looking into any time soon 🥲
