### ISSUE TITLE
Should `AutoConstructor` generate permutations based on default values?

### ISSUE THREAD

**Issue by hawkerm** [Sergio0694/ComputeSharp#151]
I can modify the new #147 FourColorGradient sample to have public colors like so:

```cs
[AutoConstructor]
internal readonly partial struct FourColorGradient : IPixelShader<float4>
{
    /// <summary>
    /// The current time since the start of the application.
    /// </summary>
    public readonly float time;

    // Colors to blend together
    public readonly float3 colorOne = new(0.999f, 0.999f, 0.999f);
    public readonly float3 colorTwo = new(0.999f, 0f, 0f);
    public readonly float3 colorThree = new(0f, 0.999f, 0f);
    public readonly float3 colorFour = new(0f, 0f, 0.999f);
```

But then the constructor generated by `AutoConstructor` assumes that those colors are also required...

I can add a simple time constructor still manually:

```cs
    public FourColorGradient(float time)
    {
        this.time = time;
    }
```

This maintains the behavior I want to keep if I want to initialize and use the default colors.

Should this be handled where the AutoConstructor can basically make alternate constructors where other values which are provided a default don't have to be provided?

i.e. adding automatically:

```cs
FourColorGradient(float time)
FourColorGradient(float time, float3 colorOne)
FourColorGradient(float time, float3 colorOne, float3 colorTwo)
FourColorGradient(float time, float3 colorOne, float3 colorTwo, float3 colorThree)
FourColorGradient(float time, float3 colorOne, float3 colorTwo, float3 colorThree, float3 colorFour)
```

instead of just the last one today...

**Comment by Sergio0694** [comment]
Are those colors meant to be changed at runtime? If they're just meant to be kinda like constants (ie. fixed in source and never changed at runtime), make them static readonly fields instead. They'll be skipped by the constructor generator, they'll generate more optimized code, and the behavior at runtime will be the same 🙂

**Comment by hawkerm** [comment]
In this case, I had two scenarios. One where I just wanted to initialize it simply with the defaults, and another one where they'd change dynamically at runtime.
