### ISSUE TITLE
Update Readme with Link to HLSL to GLSL guide

### ISSUE THREAD

**Issue by hawkerm** [Sergio0694/ComputeSharp#152]
When working on adding a new shader from ShaderToys in #147.

I was a bit confused on how to map some of the GLSL functions to the HLSL equivalents used in ComputeSharp.

@Sergio0694 pointed out a good blog he uses: https://anteru.net/blog/2016/mapping-between-HLSL-and-GLSL/

Would be handy to add this to the readme for others that may need it in the future.

**Comment by Sergio0694** [comment]
Sorry for the slight delay 😅

Good suggestion! Added a link to that [to the wiki](https://github.com/Sergio0694/ComputeSharp/wiki/3.-Getting-started-%F0%9F%93%96). Thank you! 😄
