### ISSUE TITLE
Spir-V

### ISSUE THREAD

**Issue by SupinePandora43** [Sergio0694/ComputeSharp#170]
If ComputeSharp works like https://github.com/mellinoe/ShaderGen (c# to shader) then it should be totally possible to use Spir-V compilators to compile HLSL to other shading languages for using  with other backends?

**Comment by john-h-k** [comment]
HLSL -> SpirV comes with many caveats and is no longer actively maintained.

Also, SpirV -> MSL/etc is weak at best. I would not trust it
