### ISSUE TITLE
Compilation error implementing IComputeSharer in v2.0.0-alpha.9

### ISSUE THREAD

**Issue by atonalfreerider** [Sergio0694/ComputeSharp#185]
### Reproduction Steps
Using this code from the sample:

```CSharp
[AutoConstructor]
public readonly partial struct SomeShader : IComputeShader
{
    public readonly ReadWriteBuffer<int> buffer;
    
    public void Execute()
    {
        
    }
}
```
there is a compilation error. The compiler is complaining that the obsolete members of IShader are not implemented (e.g. GetDispatchId, LoadDispatchData, etc). The `partial` keyword is also greyed-out.

### System info

- **ComputeSharp v2.0.0-alpha.9** 
- Recently upgraded from alpha.6, and made sure that there was a clean install from nuget

**Comment by Sergio0694** [comment]
Hi @atonalfreerider 👋
The `alpha.9` version switched the source generators to incremental generators, and as such they require VS2022 (or Rider) to work. Would you happen to be using VS2019 by any chance? That would explain the issue. 🤔

**Comment by atonalfreerider** [comment]
Thank you for the response - and I love this library.

I should have mentioned that I primarily use Rider. I'm currently running Rider 2021.2.3. 

I just installed VS2022. I also changed `<TargetFramework>net6.0</TargetFramework>` in my csproj and upgraded my .NET version from 2.1.801 to 6.0.101 in the Rider Environment settings. This version was not the default, even with my latest Rider update.

The `SomeShader` is now compiling. However, `partial` is still greyed-out. This would indicate that the `[AutoConstructor]` is failing? I can't pass the buffer when I call `SomeShader someShader = new(bufferParameter)`  because the compiler is saying that `SomeShader` takes 0 arguments.

**Comment by atonalfreerider** [comment]
I'm realizing I might be having a few more issues than those described above. I pushed a branch on my code (it's a Force Directed Graph):
https://github.com/atonalfreerider/GPU-FDG/tree/computesharp-9

I'm currently also getting this error when attempting to build:
```
System.NotSupportedException: Runtime shader compilation is not supported by the current configuration.
   at Microsoft.Toolkit.Diagnostics.ThrowHelper.ThrowNotSupportedException(String message)
   at ComputeSharp.Shaders.Dispatching.ShaderBytecodeLoader.LoadDynamicBytecode(IntPtr handle) in /_/src/ComputeSharp/Shaders/Dispatching/ShaderBytecodeLoader.cs:line 48
   at GPU_FDG.ForceKernelShader.global::ComputeSharp.__Internals.IShader.LoadBytecode[TLoader](TLoader& loader, Int32 threadsX, Int32 threadsY, Int32 threadsZ) in C:\Users\johnb\Desktop\PRIMITIVE-Tools\LAYOUT\GPU-FDG\ComputeSharp.SourceGenerators\ComputeSharp.SourceGenerators.IShaderGenerator\GPU_FDG.ForceKernelShader.LoadBytecode.cs:line 19
   at ComputeSharp.Shaders.ShaderRunner`1.LoadShader(Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader, ICachedShader& shaderData) in /_/src/ComputeSharp/Shaders/ShaderRunner{T}.cs:line 230
   at ComputeSharp.Shaders.ShaderRunner`1.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader) in /_/src/ComputeSharp/Shaders/ShaderRunner{T}.cs:line 133
   at ComputeSharp.Shaders.ShaderRunner`1.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, T& shader) in /_/src/ComputeSharp/Shaders/ShaderRunner{T}.cs:line 83
   at ComputeSharp.GraphicsDeviceExtensions.For[T](GraphicsDevice device, Int32 x, T& shader) in /_/src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Dispatching.cs:line 21
```

**Comment by Sergio0694** [comment]
> "I'm currently also getting this error when attempting to build"

To clarify, that is a typo and you got that error at runtime, correct?
This is due to the fact I've split up the runtime shader compilation feature into a separate package: `ComputeSharp.Dynamic`.
Basically:
- `ComputeSharp` has the core APIs and only supports running precompiled shaders (using `[EmbeddedBytecode]`)
- `ComputeSharp.Dynamic` enables runtime shader compilation too

If you're just running your shader with a loop over the X axis and your shader are not dynamic (ie. they don't capture a delegate), you don't need runtime shader compilation. Just add `[EmbeddedBytecode(32, 1, 1)]` to your shader, and then run your shader as `GraphicsDevice.For(<COUNT>, 1, 1, 32, 1, 1, <YOUR_SHADER>)`. If you otherwise just want the easier API with runtime shader compilation, just also add a reference to `ComputeSharp.Dynamic`.

Let me know if it works! 🙂

**Comment by atonalfreerider** [comment]
Thank you - **inluding ComputeSharp.Dynamic worked**. Oddly, the `partial` keyword grey-out and the constructor error only appear in Rider. They do not appear in VS2022. Rider shows a warning that not all .NET 6 features are supported yet, so I'm sure that's just an error with the current Rider release.

ComputeSharp is by far the easiest .NET library I've ever used to do GPU related projects. Thank you for the great work. You might consider adding a section in the readme for upgrading from earlier versions of ComputeSharp to the current one, that would include the changeover that is explained in this issue ticket.

Please take a look at the Force Directed Graph I made with your library. I use it as a part of my VR code visualization tool I built. The tool is designed to help open source maintainers to explain their code to people. Open to collaboration if you want to use the tool to look at the ComputeSharp source code: https://primitive.io

**Comment by Sergio0694** [comment]
Glad that worked, and thank you for your support! Really happy to hear the library is being useful for you! 😄

> "consider adding a section in the readme for upgrading from earlier versions of ComputeSharp"

Note that ComputeSharp is still in alpha, as I'm still adding APIs and making all sorts of breaking changes.
Don't expect not to ever have errors when updating between other alpha releases 😅

I do feel like I'm finally getting close to a stable release though! 🥳
