### ISSUE TITLE
Can I use the repo to split video file?

### ISSUE THREAD

**Issue by zydjohnHotmail** [Sergio0694/ComputeSharp#212]
Hello:
I found the repo., it seems to be promising.  I have a question: can I use the repo to split a MP4 format video?
For example, I have one MP4 file: C:\Videos\1.mp4, which has a duration of 2 minutes.
I want to split the MP4 file, to have the first minute video in another MP4 file.  For example, in FFMPEG, I can use the following command to get the file:
C:\Videos\> ffmpeg -i 1.mp4 -ss 0 -to 0:1:0 minute1.mp4
I want to know if I can use the repo to get the same file just as the above ffmpeg command?
By the way, my PC (Windows 10) has one NVIDIA GEFORCE GT1030 graphics card, I think it has some GPU inside it.  But I don’t if I can use the repo to use the built-in GPU from the graphics card.
So, I want to know if the repo can’t use GPU, then can I simply run the code to use only CPU?
I have both Visual Studio 2019 and 2022.
Thanks,

**Comment by Sergio0694** [comment]
ComputeSharp doesn't include any video codecs or other facilities to decode video frames from videos, no. You can certainly use ComputeSharp to _process_ video frames in some way after extracting them (eg. loading them as textures and running some shader on them), but there's no APIs to get those frames from just a raw MP4 file or anything like that 🙂
