### ISSUE TITLE
Add support for PascalCase in shader field names

### ISSUE THREAD

**Issue by moorehousew** [Sergio0694/ComputeSharp#213]
### Description

Shaders should compile properly if field names are in Pascal-case (or any case, really).

### Proposed API

The HLSL generator can internally rename these fields to the proper casing.
ex. `public readonly ReadWriteBuffer<float> Buffer;` should be equivalent to `public readonly ReadWriteBuffer<float> buffer;`

### Alternatives

Add support for private shader fields such that the normative casing is lower-case anyways.

**Comment by Sergio0694** [comment]
Not sure I understand the issue, you can already use uppercase fields just fine? 🤔

Eg. this works:

```csharp
internal readonly partial struct MultiplyByTwo : IComputeShader
{
    public readonly ReadWriteBuffer<float> Buffer;

    /// <inheritdoc/>
    public void Execute()
    {
        Buffer[ThreadIds.X] *= 2;
    }
}
```

Is there a specific snippet of code that's failing to compile for you?

**Comment by Sergio0694** [comment]
Closing this as no repro since the author didn't reply.
That snippet I shared compiles fine, so I'm not sure I see the issue.
