### ISSUE TITLE
Add support for pixel shaders and Direct2D

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#214]
We've talked about this on Discord, so here's an issue to keep track of it :)

Paint.NET would benefit immensely from being able to support pixel shaders authored with something like ComputeSharp. Right now I have to write the HLSL by hand and wire up a pre-build event to run `fxc.exe`, etc. Converting the built-in shaders would be nice, but the biggest win would be so that plugins can have a simple way of authoring HLSL shaders. (some quick background: for my next big release, I'm adding the ability for effect plugins to use Direct2D, along with its effects framework that includes the ability to run custom/arbitrary pixel shaders)

So, in order to support this scenario, ComputeSharp would need both 1) support for authoring pixel shaders, 2) support for Direct2D's helper library, and 3) the ability to compile a shader to support shader linking.

For 1, the ComputeSharp API would need additions to support the way pixel shaders do things vs. compute shaders. I think it's mostly a reduction in features, e.g. no "thread groups" for X,Y,Z stuff.

For 2, Direct2D requires you to have `#include "d2d1effecthelpers.hlsli"` which includes several macros and functions. Docs are here https://docs.microsoft.com/en-us/windows/win32/direct2d/hlsl-helpers and I have a sample shader here that uses a few of them https://github.com/paintdotnet/PdnGpuEffectSamples/blob/main/RippleTransform.Shader.ps_4_0.hlsl

For 3, shader linking involves running `fxc.exe` twice as documented here https://docs.microsoft.com/en-us/windows/win32/direct2d/effect-shader-linking#authoring-a-shader-linking-compatible-custom-effect . My batch file that does this is here https://github.com/paintdotnet/PdnGpuEffectSamples/blob/main/buildD2DHLSL.cmd

**Comment by rickbrew** [comment]
Also, Paint.NET will not need ComputeSharp to _execute_ the pixel shaders. I just need the compiled bytes for the shader. Direct2D will do all of the executing. It would also be helpful to have a way to access the generated HLSL so it can be inspected.

**Comment by rickbrew** [comment]
Direct3D has its own shader linking stuff, btw https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/constructing-a-function-linking-graph

**Comment by Sergio0694** [comment]
Alright, as discussed on Discord too, this sounds awesome 😄

I'm thinking a good way to approach this would be to start by not worrying about linked shaders in a v1.0 version.
We could add support for this as a separate additional module for ComputeSharp.

The following packages would have to be added:
- **ComputeSharp.D2D1Interop**: containing all the support APIs to write D2D1-compliant pixel shaders.
- **ComputeSharp.D2D1Interop.SourceGenerators**: with the generator specific for D2D1. This might also just be included in the current source generator package, but with additional logic to detect whether D2D1 types are present, and to properly handle them. Either would work, so we'll see down the line which approach ends up making more sense.

As far as supporting D2D1 shaders, I'm thinking we'd need the following new APIs in the D2D1 package:

```csharp
namespace ComputeSharp.D2D1Interop.__Internals
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This interface is not intended to be used directly by user code")]
    public interface ID2D1Shader
    {
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("This method is not intended to be called directly by user code")]
        void LoadDispatchMetadata<TLoader>(ref TLoader loader, out IntPtr result)
            where TLoader : struct, IDispatchMetadataLoader;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("This method is not intended to be called directly by user code")]
        void BuildHlslString(out ArrayPoolStringBuilder builder);

        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("This method is not intended to be used directly by user code")]
        void LoadBytecode<TLoader>(ref TLoader loader)
            where TLoader : struct, IBytecodeLoader;
    }
}

namespace ComputeSharp.D2D1Interop
{
    public interface ID2D1PixelShader : ID2D1Shader
    {
        float4 Execute();
    }

    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class InputCountAttribute : Attribute
    {
        public InputCountAttribute(int size);

        public int Size { get; }
    }

    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = true)]
    public sealed class InputSimpleAttribute : Attribute
    {
        public InputSimpleAttribute(int index);

        public int Index { get; }
    }

    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = true)]
    public sealed class InputComplexAttribute : Attribute
    {
        public InputComplexAttribute(int index);

        public int Index { get; }
    }

    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class RequiresScenePositionAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class CustomEntryAttribute : Attribute
    {
    }

    public static class D2D1
    {
        public static float4 GetInput(uint index);
        public static float4 GetInputCoordinate(uint index);
        public static float4 GetScenePosition();
        public static float4 SampleInput(uint index, float2 uv);
        public static float4 SampleInputAtOffset(uint index, float2 offset);
        public static float4 SampleInputAtPosition(uint index, float2 uv);
    }
}
```

Thankfully it seems there isn't too much API surface we'd need to cover. Some open questions:

- Not 100% sure on `LoadDispatchMetadata`, will need to see how are D2D1 shaders expecting captured values.
- Do pixel shaders always return `float4` or do we need to make the shader type generic (eg. to return `float3`)?
- The attribute names might be improved, but really the same can be said about all of these APIs (just a draft)
- `RequiresScenePositionAttribute` might technically be auto-detected by the generator, and not needed. There's a question as to whether it'd be better to have more explicitness, or whether the implicit behavior would be better. Given the advanced nature of this set of APIs I'm inclined to say the explicit attribute makes sense, but I'm open to suggestions.

I think the next steps should be:

- Explore building a bytecode from ComputeSharp from a handcrafted HLSL source, just to verify compiling shaders would work with no issues. Then everything else would just build on top anyway and mostly be a matter of repurposing existing APIs, and adding the new ones and plugging them into the existing architecture.
- Iterate on the API shape as well while the point above is being explored.

**Comment by Sergio0694** [comment]
Updating here following our last conversation. Given it seems the dispatch side only needs to supply the constant buffer data for the shader, but doesn't actually need to create a root signature for it (hence no need for dispatch metadata), I think the definition of the generated APIs should be changed a bit for the base D2D1 shader type. Something like:

```csharp
namespace ComputeSharp.D2D1Interop.__Internals
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This interface is not intended to be used directly by user code")]
    public interface ID2D1Shader
    {
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("This method is not intended to be called directly by user code")]
        void LoadDispatchData<TLoader>(ref TLoader loader)
            where TLoader : struct, IDispatchDataLoader;

        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("This method is not intended to be called directly by user code")]
        void BuildHlslString(out ArrayPoolStringBuilder builder);

        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("This method is not intended to be used directly by user code")]
        void LoadBytecode<TLoader>(ref TLoader loader)
            where TLoader : struct, IBytecodeLoader;
    }
}
```

Where Paint.NET would implement its own `IDispatchDataLoader` type, which would call [ID2D1DrawInfo::SetPixelShaderConstantBuffer](https://docs.microsoft.com/en-us/windows/win32/api/d2d1effectauthor/nf-d2d1effectauthor-id2d1drawinfo-setpixelshaderconstantbuffer) passing the input `ReadOnlySpan<byte>` buffer passed by the generated method.

**Comment by Sergio0694** [comment]
After some more thought, I decided to not support dynamic shaders in `ComputeSharp.D2D1Interop`. It's a very niche feature and the main reason for it was to support ML scenarios. I don't really expect developers writing D2D1 shaders using it, and even then, it's still doable by just writing multiple shaders anyway. Removing this would support the generators a lot (no more need to also analyzer annotated methods scattered around, but just inspecting the shader is enough as they're independent). This also allows the interface definition to be simpler. Here is the updated API surface for all internal D2D1 interfaces:

```csharp
namespace ComputeSharp.D2D1Interop.__Internals;

public interface ID2D1BytecodeLoader
{
    void LoadDynamicBytecode(IntPtr handle);
    void LoadEmbeddedBytecode(ReadOnlySpan<byte> bytecode);
}

public interface ID2D1DispatchDataLoader
{
    void LoadConstantBuffer(ReadOnlySpan<uint> data);
}

public interface ID2D1Shader
{
    void LoadDispatchData<TLoader>(ref TLoader loader)
        where TLoader : struct, ID2D1DispatchDataLoader;

    void LoadBytecode<TLoader>(ref TLoader loader, out string hlslSource)
        where TLoader : struct, ID2D1BytecodeLoader;
}
```

> **NOTE:** I've left out the various `[Obsolete]` and `[EditorBrowsableState]` attributes here for clarity, but they're there.
