### ISSUE TITLE
Add "ComputeSharp" nuget packge to netstandard 2.1 project will break build

### ISSUE THREAD

**Issue by JohnMasen** [Sergio0694/ComputeSharp#217]
### Description (optional)

ComputeSharp generated file GlobalUsingDirectives.cs is using C# 10 global using directive which is not supported in netstandard 2.1 project.

### Reproduction Steps

1. Create a netstandard 2.1 project
2. Add "ComputeSharp" nuget package reference
3. Build project

### Expected Behavior

project build successful

### Actual Behavior
build fail with error  "_CS8400	Feature 'global using directive' is not available in C# 8.0. Please use language version 10.0 or greater_"	error at file GlobalUsingDirectives.cs

### Suggestion
As ComputeSharep requires dotnet 6, It would be good to add version dependency to Nuget package to avoid confusing.

### System info

This section should contain useful info such as:
- **ComputeSharp** **NuGet v 2.0.0-alpha19**
- Operating system version : **Windows 11**
- CPU/GPU model (the latter is especially useful for shader issues): **Not related**
- Visual Studio version, or .NET SDK/runtime version **VS2022**

**Comment by Sergio0694** [comment]
Hey there! ComputeSharp requires C# 10 to work, but that's not restricted to .NET 6 🙂
For instance, you can see the solution even has some test projects and samples running on .NET Framework 4.7.1 😄

You just need to enable C# 10 manually if you're below .NET 6. Just add this to the first `<PropertyGroup>` in your .csproj:

```xml
<LangVersion>10.0</LangVersion>
```

This will enable C# 10 and solve the issue 👍

**Comment by JohnMasen** [comment]
Thanks for your advice, it works!
may I suggest adding a tip to the document about this?
