### ISSUE TITLE
Can't compile `Hlsl.Mul(float3x2, float2).XY`

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#232]
I'm not sure my math is correct for what I'm trying to do, but I'd expect this to compile since it's just using basic swizzling:

`D:\src\pdn\src\Effects\Effects\Gpu\RadialBlurGpuEffect.cs(261,37,261,52): error CMPSD2D0034: The shader of type PaintDotNet.Effects.Gpu.RadialBlurGpuEffect.SampleMapShader failed to compile due to an HLSL compiler error (Message: "The FXC compiler encountered one or more errors while trying to compile the shader: [error X3014]: incorrect number of arguments to numeric-type constructor. Make sure to only be using supported features by checking the README file in the ComputeSharp repository: https://github.com/Sergio0694/ComputeSharp. If you're sure that your C# shader code is valid, please open an issue an include a working repro and this error message.")`

```cs
[D2DInputCount(0)]
[D2DRequiresScenePosition]
[D2DEmbeddedBytecode(D2D1ShaderProfile.PixelShader50)]
[AutoConstructor]
private readonly partial struct SampleMapShader
    : ID2D1PixelShader
{
    private readonly float3x2 transform;

    public float4 Execute()
    {
        float2 scenePos = D2D.GetScenePosition().XY;
        float2 inputPos = Hlsl.Mul(this.transform, scenePos).XY; // fxc seems to hate the .XY on this
        return new float4(inputPos, 0);
    }
}
```

BTW _this_ works: (well it compiles at least)

```
    public float4 Execute()
    {
        float2 scenePos = D2D.GetScenePosition().XY;
        float3 inputPos3 = Hlsl.Mul(this.transform, scenePos);
        float2 inputPos2 = inputPos3.XY;
        return new float4(inputPos2, 0, 0);
    }
```

**Comment by Sergio0694** [comment]
This seems to be a bug in FXC, the generated HLSL is otherwise valid. It also works just fine when using DXC.

To repro, paste this in https://shader-playground.timjones.io/ and set the compiler to FXC and the profile to `ps_5_0`:

```hlsl
float4 PSMain() : SV_Target
{
    float3x2 transform = 0;
    float2 scenePos = 0;
    float2 inputPos = mul(transform, scenePos).xy;
    return float4(inputPos, 0);
}
```

**Comment by rickbrew** [comment]
okay well at least that's solved 🤷🏼‍♂️
