### ISSUE TITLE
Need a `D2D1PixelShaderEffectProperty` class

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#237]
Right now a user of the `D2D1PixelShaderEffect` needs to use a magic number, `0`, for setting the property that takes the shader bytecode

<img width="442" alt="image" src="https://user-images.githubusercontent.com/10873410/165139840-15c4d983-1fe8-4f61-9d20-e46e8d790714.png">

As per Direct2D convention, this would go into a `D2D1PixelShaderEffectProperty` class or enum

```cs
public static class D2D1PixelShaderEffectProperty
{
    /// <summary>
    /// Description goes here, along with link to the method used for getting the const buffer
    /// This property is of type Blob etc.
    /// </summary>
    public const int ConstantBuffer = 0;
}
```

**Comment by rickbrew** [comment]
bump :) I think this is an important one for usability of the PixelShaderEffect, and provides a place to add more properties such as the input description overrides

**Comment by Sergio0694** [comment]
We should plan ahead and come up with a list of names for all possible properties we might need, to make them consistent. As far as I know, at least for now, we should/might have:
- Constant buffer
- Input0Description
- ...
- Input7Description
- D2D1Resource0
- ...
- D2D1Resource7

Something like that?

**Comment by rickbrew** [comment]
I'd be happy to start with the one property we already have and are making use of :)

I don't believe you can define custom sub-properties.

**Comment by rickbrew** [comment]
Also this should probably be named singular, `D2D1PixelShaderEffectProperty` (i've edited the title to match)

**Comment by rickbrew** [comment]
> I'd be happy to start with the one property we already have and are making use of :) We can always rename things to keep them consistent.

The reason I say this is that is currently a sorely needed feature, and I don't want to get stuck in committee meetings figuring out a naming scheme for 1) something that might not even happen, and 2) something that can easily be revised later. Let's just get this one property in for now :)
