### ISSUE TITLE
Can't compile shader when system set to Turkish locale

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#238]
This is preventing @otuncelli from compiling the PDN Sample GPU Effects

https://forums.getpaint.net/topic/119941-paintnet-44-alpha-build-8149-pixel-shaders-are-go/?do=findComment&comment=595185

> I'm using VS 2022 v17.1.0 ... I've an idea about this error. I'm using Turkish locale on my computer. As you can see, it generates uınt2, not uint2. I think it's something to do with my locale settings.
...
> Yup, I can confirm. Changing locale to US, English solves the problem.

**Comment by Sergio0694** [comment]
...I can't with localization in .NET sometimes 🤦‍♂️
