### ISSUE TITLE
Add `ID2D1PixelShader.GetInputFilter()` API, with appropriate attributes to define it

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#261]
Another part of allowing pixel shaders to be self-describing is the notion of specifying the _filter_ for an input. This is established for the shader in the `ID2D1DrawTransform` by calling `ID2D1RenderInfo::SetInputDescription()` (`ID2D1DrawInfo` implements `ID2D1RenderInfo`).

I propose making this part of the attribute for defining the input itself, something like

```cs
[D2DInputCount(2)] // could technically get rid of this actually
[D2DInput(0, PixelShaderInputType.Simple, PixelShaderInputFilter.MinMagMipPoint)]
[D2DInput(1, PixelShaderInputType.Complex, PixelShaderInputFilter.MinMagMipLinear)]
public readonly partial struct MyShader 
    : ID2D1PixelShader
{
    ...
}
```

There's also a `levelOfDetailCount` parameter that `SetInputDescription` takes, but I've always set this to `0`. It's worth including so it doesn't need to be added later, and can just default to `0`.

All of the information about an input: index, type (simple vs. complex), filter, and level-of-detail, could be bundled up into something like a `PixelShaderInputDescription` struct, but doesn't have to be.

**Comment by rickbrew** [comment]
Many shader authors won't know what "minmagmip" means. So setting a reasonable default is a good idea -- probably `MinMagMipLinear`.

**Comment by Sergio0694** [comment]
I was not convinced about this one at first, but I do see the point of just being able to have shaders be fully self describing, plus the fact this would allow `D2D1PixelShaderEffect` to also use the API internally to set the input descriptions. I'm just not a fan of the proposed API surface, as I feel it clashes a bit with the existing `D2D1InputSimple` and `Complex`. Or, if this was proposed as a replacement, then it'd mean we'd no longer have that clean mapping to the macros in the D2D header.

I need to think about this some 🤔

**Comment by Sergio0694** [comment]
Also, are there reasonable cases where one would want to change the description of an input and not have it be fixed? This approach would hardcode it into the pixel shader effect, and I don't have enough context to say whether someone needing to do that would just be an extremely niche scenario we might just decide not to support, or whether it should be a concern.

**Comment by rickbrew** [comment]
I could see wanting to change the input description for switching between point and linear sampling, based on a property provided by a fully custom effect. Point sampling is faster, and (obviously) has a different aesthetic.

You could provide a means to override the input description. So maybe the input description that's stapled onto a shader could be called the _default_ or _requested_ input description. And the default for the default is Unknown buffer precision and Default channel depth, which is pretty reasonable.

The other issue is that having the shader define its input descriptions is only applicable when the thing hosting the pixel shader is honoring it. It's not actually intrinsic to the shader, in other words. I think this is fine as long as you call it out in a comment or doc somewhere.
