### ISSUE TITLE
Add `ID2D1PixelShader.GetOutputBuffer()` and attributes

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#262]
Another thing to help shaders be self-describing is the ability to specify the output buffer's characteristics. There are two values here, one for the buffer precision (e.g. U8, F32, F16, Unknown), and one for the channel depth (1 vs. 4).

The default if you don't call `ID2D1RenderInfo::SetOutputBuffer()` is Unknown/Default precision, and Default channel depth. This causes D2D to look around at the larger context to figure it out, which is often fine, but not always. There's a flow chart at the bottom of https://docs.microsoft.com/en-us/windows/win32/direct2d/precision-and-clipping-in-effect-graphs that describes it all. 

When processing colors, you usually just want to use the default/unknown value for buffer precision. However, for other purposes (like sample maps or other non-color outputting shaders) you probably want Float32. Having an easy way for a shader to self-describe this to the rest of the infra is important so that a shader author doesn't have to write a transform/mapper from scratch just to ensure they get the right precision.

```cs
[D2DInputCount(...)]
[D2DInput...]
[D2DOutputBuffer(BufferPrecision.Float32bpc, ChannelDepth.Four)]
public readonly partial struct MyShader
    : ID2D1PixelShader
{
...
}
```

The ChannelDepth can have a default value of Four, it's not really common to use One.

**Comment by Sergio0694** [comment]
This makes sense, and I can see how having an API would be needed in order for the built-in effect to plug this in.
I'm thinking `BufferPrecision` should be `D2D1BufferPrecision`, and `ChannelDepth` should be `D2D1ChannelDepth`, for consistency. We might also expose constructors only taking precision/depth, and both, to give users more flexibility. These would then go through a new internal `ID2D1Shader` API, a public `D2D1PixelShader` API, and then `D2D1PixelShaderEffect` would also use it internally to set the output buffer if any of the two values is not the default.
