### ISSUE TITLE
`const` expression inside method is broken, uses int instead of float/double

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#279]
This is from the same shader that's included in https://github.com/Sergio0694/ComputeSharp/issues/278

If we change this:

```cs
private const float r255 = (float)(1.0 / 255.0);
private void UpdateCellData(int xi, int yi, ref CellData cd)
{
    ...
}
```

to this:

```cs
private void UpdateCellData(int xi, int yi, ref CellData cd)
{
    const float r255 = (float)(1.0 / 255.0);    
    ...
}
```

The code gen for `r255` changes from a `#define` at the top, like so:
```hlsl
#define __PaintDotNet_Effects_Gpu_CrystalizeGpuEffect_SampleMapShader__r255 0.003921569
```

To a local const value that is _completely wrong_ 😁

```hlsl
void UpdateCellData(int xi, int yi, inout PaintDotNet_Effects_Gpu_CrystalizeGpuEffect_SampleMapShader_CellData cd)
{
    const float r255 = (float)(1L / 255L); // Umm excuse me, I ordered a float, not a long
    ...
}
```

Which causes the output of the Crystalize distortion effect to go from this:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/10873410/169435462-16e71ab4-325f-496b-91ec-7fccfd92f53b.png">

to this:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/10873410/169435517-ac5bf811-5baf-404b-a06f-7adb9e3e60b8.png">

**Comment by Sergio0694** [comment]
I suspect there might be two different bugs here:

- I'm seemingly not detecting constants declared withing a method (I think I might've just forgotten about those being a thing), so they're not being rewritten properly as constants but instead just rewritten like normal values. So I should fix that.
- There also seems to be something weird here with those double values being rewritten as longs. That's also weird.
