### ISSUE TITLE
D2D1ReflectionServices.GetShaderInfo() should not recompile shader

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#284]
This method is recompiling the HLSL to bytecode, but it doesn't have to do that -- in fact, it's doing it incorrectly because it always uses `D2D1ShaderProfile.PixelShader50` and `D2D1CompileOptions.Default`

**Comment by rickbrew** [comment]
Looks like this is the underlying causes of #282, because I always grab the `ShaderInfo` so that I can call `ID2D1RenderInfo::SetInstructionCountHint()`

**Comment by Sergio0694** [comment]
Closed by 7b02a1156e9952740469f15b74b1a94862f64bc1.
