### ISSUE TITLE
`D2D1PixelShader` class ... should not be in the Interop namespace?

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#290]
Getting the const buffer doesn't seem like a very interop-y thing 🤔 It's a mainline scenario for working with the shader and the `D2D1PixelShaderEffect`

**Comment by Sergio0694** [comment]
We've talked about this already, all APIs that are strictly for then plugging pixel shaders into the D2D1 infrastructure are conceptually interop. Getting the constant buffer is already a kind of interop, as it represents the aligned dispatch data for the shader, which is only useful in an interop scenario, ie. when passing that to an `ID2D1DrawInfo` object 🙂

Essentially:
- ComputeSharp.D2D1 contains all APIs to define and implement shaders
- ComputeSharp.D2D1.Interop contains all APIs to then connect these shaders with the D2D1 infrastructure

I'd prefer to leave the two as they are, I do like the conceptual separation there.
Plus ComputeSharp.D2D1 is already pretty crammed 😄
