### ISSUE TITLE
D2D1ShaderCompiler is renting, but not returning, arrays

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#300]
Surely that was not your intention? :)

https://github.com/Sergio0694/ComputeSharp/blob/745f23a3a1b8d2fb18a32727c6f5bd2135fee29e/src/ComputeSharp.D2D1/Shaders/Interop/D2D1ShaderCompiler.cs#L34

![image](https://user-images.githubusercontent.com/10873410/170832815-36034aad-6e41-4104-bff9-d38d43df387d.png)

**Comment by Sergio0694** [comment]
Already fixed in 745f23a3a1b8d2fb18a32727c6f5bd2135fee29e, try to keep up Rick! 😛
