### ISSUE TITLE
Can't get program to compile.

### ISSUE THREAD

**Issue by Gavin-Williams** [Sergio0694/ComputeSharp#311]
Sorry about the vague question. I've just started using ComputeSharp and I don't have any idea about what's wrong here. I'm trying to generate primary rays into a buffer for a software raytracer. And I can't get the program to compile. The error is 

> CMPS0047 The shader of type Demo.GeneratePrimaryRays needs to be annotated as having embedded bytecode (using the [EmbeddedBytecode] attribute), as dynamic shader compilation is not supported

But adding the EmbeddedBytecode attribute just leads to more problems that I don't understand. So can anyone make some suggestions as to what to do here?

```
   //[AutoConstructor]
    //[EmbeddedBytecode]
    public readonly partial struct GeneratePrimaryRays : IComputeShader
    {
        public readonly ReadWriteBuffer<Vector3> Buffer;
        public readonly Vector3 CameraPosition;
        public readonly float4x4 WorldViewProjMatrix;
        public readonly int XPixels;
        public readonly int YPixels;

        public GeneratePrimaryRays(
            ReadWriteBuffer<Vector3> buffer,
            Vector3 cameraPosition,
            float4x4 worldViewProjMatrix,
            int xPixels,
            int yPixels)
        {
            Buffer = buffer;
            CameraPosition = cameraPosition;
            WorldViewProjMatrix = worldViewProjMatrix;
            XPixels = xPixels;
            YPixels = yPixels;
        }

        public void Execute()
        {
            int x = ThreadIds.X % XPixels;
            int y = ThreadIds.X / XPixels;
            float3 scrnVec = new Vector3(x, y, 1);
            Vector3 wrldVec = Unproject(
                ref scrnVec,
                0, 0, XPixels, YPixels,
                0.1f, 1000,
                WorldViewProjMatrix);
            wrldVec = Vector3.Normalize(wrldVec);
            Buffer[ThreadIds.X] = wrldVec;
        }

        private float3 Unproject(
            ref float3 vector, 
            float x, float y, 
            float width, float height, 
            float minZ, float maxZ, 
            float4x4 worldViewProjection)
        {
            float3 v = new();
            float4x4 matrix = InvertMatrix(worldViewProjection);
            v.X = (((vector.X - x) / width) * 2.0f) - 1.0f;
            v.Y = -((((vector.Y - y) / height) * 2.0f) - 1.0f);
            v.Z = (vector.Z - minZ) / (maxZ - minZ);

            //Vector3 result = Vector3.Transform(v, matrix);
            float4 result = Hlsl.Mul(new float4(v,1), matrix);
            return result.XYZ;
        }

        private static float4x4 InvertMatrix(float4x4 matrix)
        {
            return new Float4x4(
                matrix.M11, matrix.M21, matrix.M31, matrix.M41,
                matrix.M12, matrix.M22, matrix.M32, matrix.M42,
                matrix.M13, matrix.M23, matrix.M33, matrix.M43,
                matrix.M14, matrix.M24, matrix.M34, matrix.M44);
        }
    }
```

**Comment by Sergio0694** [comment]
> "CMPS0047 The shader of type Demo.GeneratePrimaryRays needs to be annotated as having embedded bytecode (using the [EmbeddedBytecode] attribute), as dynamic shader compilation is not supported"

This is happening if you're not referencing `ComputeSharp.Dynamic`, which bundles the compiler used to compile shaders at runtime. If you don't have that, then you have to precompile shaders at compile time, which is enabled when using the `[EmbeddedBytecode]` attribute. I guess I might improve the error message to mention `ComputeSharp.Dynamic` 🙂

See the wiki about this [here](https://github.com/Sergio0694/ComputeSharp/wiki/3.-Getting-started-%F0%9F%93%96#precompiled-shaders-).

> "adding the EmbeddedBytecode attribute just leads to more problems that I don't understand"

This is indeed a bit vague 😅
What kind of problems do you mean exactly?

**Comment by Gavin-Williams** [comment]
Well the attribute itself has red squiggles. And the error is ..

> EmbeddedBytecodeAttribute does not contain a constructor that takes 0 arguments.

I think that's just a rabbit hole of issues though. Given that I'm not yet even thinking about precompiling the shaders. If dynamic shader compilation is OK then I'm happy to use that at the moment.

**Comment by Sergio0694** [comment]
> "EmbeddedBytecodeAttribute does not contain a constructor that takes 0 arguments"

I mean, the message is telling you exactly what the error is. There are no parameterless constructor for that attribute. You need to pass some parameters. For instance, if you're dispatching the shader over 2 dimensions, use `DispatchAxis.XY`.

> "If dynamic shader compilation is OK then I'm happy to use that at the moment"

Why? You have no reason to use that unless you specifically need dynamic features. If you precompile your shaders you'll save a lot of binary size (the shader compiler is about 20MB in size), and also get faster startup performance. Not to mention, you'll be able to spot errors in your shader at compile time, and not just when compiling the shader at runtime.

Anyway, closing this since there's no issue with ComputeSharp itself here 🙂
