### ISSUE TITLE
RWStructuredBuffer<float3> error.

### ISSUE THREAD

**Issue by Gavin-Williams** [Sergio0694/ComputeSharp#313]
This looks right to me, but I may be making a mistake. Getting the following error

> Compiler error - [error]: template specialization requires 'template<>' RWStructuredBuffer<float3> Buffer : register(u0); ~~~~~ template<> [error]: no variable template matches specialization [error]: expected unqualified-id Buffer[i] = normalize(float3(0.1, x, y)); ... F:\Projects\EngineProjects\MinimalShader\GeneratePrimaryRays.cs	12	

[MinimalShader.zip](https://github.com/Sergio0694/ComputeSharp/files/8939663/MinimalShader.zip)

Shader class:
```csharp
using ComputeSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace MinimalShader
{
    [EmbeddedBytecode(DispatchAxis.X)]
    public partial struct GeneratePrimaryRays : IComputeShader
    {
        public ReadWriteBuffer<float3> Buffer;

        public GeneratePrimaryRays(
            ReadWriteBuffer<float3> buffer)
        {
            Buffer = buffer;
        }

        public void Execute()
        {
            int i = ThreadIds.X;
            int x = i % 256;
            int y = i / 256;
            Buffer[i] = Hlsl.Normalize(new Float3(0.1f, x, y));
        }
    }
}
```
Calling code:
```csharp
using ComputeSharp;
using MinimalShader;
using System.Diagnostics;

public class Application
{
    public static void Main()
    {
        GeneratePrimaryRays shader;
        using ReadWriteBuffer<float3> buffer =
        GraphicsDevice.Default.AllocateReadWriteBuffer<float3>(256);

        shader = new GeneratePrimaryRays()
        {
            Buffer = buffer
        };

        shader.Execute();

        for (int i = 0; i < 256; i++)
        {
            Debug.WriteLine(buffer[i].ToString());
        }
    }
}
```

**Comment by Gavin-Williams** [comment]
I've tried float4, and float as well. I can't imagine that those types would have been missed. I'm going to check the readme for something I might have missed.

**Comment by Sergio0694** [comment]
Uh... This looks _really_ weird 😶
That shader looks absolutely fine to me. The error sounds like the HLSL transpilarion was messed up, but I don't see how that would be possible here. Not to mention that shader is quite similar to a lot of the ones I have in my tests, so I'm really confused here. Thank you for the minimals repro, I'll try to see if I can reproduce the same error on my end too and take a look! 🙂

**Comment by Sergio0694** [comment]
Ooooooh ok I figured it out! The issue is that name "Buffer": that's apparently not a valid identifier in HLSL, as that's the name of the generic type `Buffer<T>`, so that was causing the compilation to fail. I never thought about this, I'll need to just add all names of generic types in HLSL to the list of special identifiers to rewrite when transforming shaders into HLSL. Good catch! 😄

As a temporary workaround, just renamed the field. Eg. "Buffer2" or even just "buffer" in lowercase will work 🙂
