### ISSUE TITLE
Nooby question, best way to achieve very simple task

### ISSUE THREAD

**Issue by Vilo176** [Sergio0694/ComputeSharp#318]
Hi Sergio,

I'm making some tests to port an existing C# code into HLSL.
The C# code is really simple : perform a triangle collision test between a given Box and a bunch of triangles.

The triangles are described as Points (float3) + Indexes (int3), and never change during the whole process.
The Box is an AABB described as Center (float3) + Size (float3)
Triangles to test are given with a int[] array

The shader must iterate over all triangles and perform the test, storing the collision result in a buffer.
Here is my current code :

```
[AutoConstructor]
[EmbeddedBytecode(DispatchAxis.X)]
internal readonly partial struct ComputeShader : IComputeShader
{
	public static ReadOnlyBuffer<float3> points;
	public static ReadOnlyBuffer<int3> triangles;

	public readonly float3 bbCenter;
	public readonly float3 bbHalfSize;
	public readonly ReadOnlyBuffer<int> idsIN;
	public readonly ReadWriteBuffer<int> idsOUT;

	public void Execute()
	{
		int3 tri = triangles[idsIN[ThreadIds.X]];
		if (Intersects(points[tri.X], points[tri.Y], points[tri.Z]))
			idsOUT[ThreadIds.X] = 1;
	}

	bool Intersects(float3 v0, float3 v1, float3 v2)
	{
		...
	}
}
```

**Question 1 :**
I want to store the Mesh (points + triangles) in the GPU once and for all, because it never changes during all the process.
So I've tried with ```public static ReadOnlyBuffer<float3> points``` but it doesn't compile.
How can I store these static buffers efficiently ?

**Question 2 :**
The shader is called several times to compute collision on different "triangles ids / AABB".
Here is the calling code :
```
public int[] Cutted(Vector3d bbMin, Vector3d bbMax, int[] ids)
{
	var bbCenter = (bbMin + bbMax) / 2;
	var idsOUT = Enumerable.Repeat(0, ids.Length).ToArray();
	using var idsOUTb = GraphicsDevice.Default.AllocateReadWriteBuffer(idsOUT);
	
	GraphicsDevice.Default.For(ids.Length, new ComputeShader
	(
		new Float3((float)bbCenter.x, (float)bbCenter.y, (float)bbCenter.z),
		new Float3((float)(bbMax.x - bbMin.x)/2, (float)(bbMax.y - bbMin.y)/2, (float)(bbMax.z - bbMin.z)/2),
		GraphicsDevice.Default.AllocateReadOnlyBuffer(ids),
		idsOUTb
	));
	
	idsOUTb.CopyTo(idsOUT);
	return idsOUT.Indexed().Where(t => t.item != 0).Select(t => ids[t.index]).ToArray();
}
```

Is it better to reuse a unique shader or (as in code above) recreate one each times ?
If I recreate one each times, is it OK to call the function "Cutted" from different threads concurrently ?

Thanks !

**Comment by Sergio0694** [comment]
Hey there! 👋

> "I want to store the Mesh (points + triangles) in the GPU once and for all, because it never changes during all the process.
So I've tried with `public static ReadOnlyBuffer<float3>` points but it doesn't compile.
How can I store these static buffers efficiently ?"

That's not valid, you cannot store a buffer in a static and then access it from a shader. _However_, that doesn't mean you can't store a buffer in some static field (or anywhere else that is also kept alive for the entire process, eg. in an instance field in some object that lives forever), and then you can just pass that to your shader. That is, a shader can only access buffers that are captured in a shader field, but then those buffers can live however long you want, including for the whole process, sure 🙂

> "Is it better to reuse a unique shader or (as in code above) recreate one each times ?"

A shader is "free" to create, it's just a struct capturing the values to pass to the GPU. You can create a new one every time you need to dispatch one, its cost is pretty much the same as just calling a method and passing some parameters, so it's very very cheap. You don't have to cache a shader, just create it on the fly with the right parameters.

> "is it OK to call the function "Cutted" from different threads concurrently ?"

Yes, you can access a `GraphicsDevice` concurrently and dispatch threads from multiple threads, that's fine. However, if any of the buffers you use in the shader is writeable and it's shared across threads, do note that you might have race conditions there.

___

Separate point, but do note that your `Cutted` method is incredibly inefficient. You're allocating two arrays and two GPU buffers every single time, plus you have a bunch of LINQ operations going on. You might want to consider optimizing that by reusing buffers and using `Span<T>` APIs in the future, if that method is used in a hot path 🙂

**Comment by Vilo176** [comment]
Hi Sergio thanks for your answers !

1. That's not what I meant ;-)
My mesh is, on C# side, a static structure that never changes.
If I use a ```ReadOnlyBuffer``` in the shader to store it, I have to transfert the whole mesh (that can have several millions of triangles) to the shader's GPU memory each time I create a shader.
This is quite inefficient.
What I ideally want is to have my mesh store GPU side in a structure accessible by any instance of my shader, and thus make the whole transfert only 1 time.
My mesh could be compared to a texture that I want to store GPU side once and for all, and later have access to it in a GPU computation.

2. Thanks for all your valuable advice !
Span<T> is definitely the way to go.

**Comment by Vilo176** [comment]
Okay Sergio, got it !
If I call ```var buffer = GraphicsDevice.Default.AllocateReadOnlyBuffer<int>(...)``` and keep it somewhere in my C# code, I can pass it to the shader ctor, and avoid memory transfert.

**Comment by Sergio0694** [comment]
Correct 🙂

There's only one "memory transfer", and that happens when you create the buffer and copy data to it. After that, if you pass any resource to a shader you're just passing its resource descriptor around so the shader knows where that data is located 👍
