### ISSUE TITLE
The types of Hlsl.Float32ToFloat16() don't match those from HLSL

### ISSUE THREAD

**Issue by Equbuxu** [Sergio0694/ComputeSharp#345]
### Description

The [f32tof16](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/f32tof16) function takes in a float and converts it into a uint, but Hlsl.Float32ToFloat16() is the opposite of that: it takes in a uint and converts it into a float.

### Reproduction Steps
Try actually using the function. I wasn't able to find any workaround that would let me actually pass it a float. I tried converting the float via Hlsl.AsUInt() with no luck (and looking at the HLSL code it's easy to tell why).

### Expected Behavior
The types should match

### Actual Behavior
The types don't match

**Comment by Sergio0694** [comment]
Whoops, small copy paste error from the `Float16ToFloat32` intrinsic definition, thank you! 😄

**Comment by Equbuxu** [comment]
Woah, that was fast, great to see a fix
