### ISSUE TITLE
Strange behaviour when capturing 2 bool values

### ISSUE THREAD

**Issue by KeterSCP** [Sergio0694/ComputeSharp#370]
### Description (optional)

I recently discovered this awesome library and wanted to play with it. So I tried to implement edge detection using [Sobel filter](https://en.wikipedia.org/wiki/Sobel_operator) in HLSL. But after adding 2 captured bool arguments to the shader, it appears that they both behave like they are always set to true, even if I set them to false.

### Reproduction Steps

- Install ComputeSharp and ComputeSharp.Dynamic packages
- Try running following sample:

```c#
using ComputeSharp;

using var device = GraphicsDevice.GetDefault();

using var imgSource = device.LoadReadWriteTexture2D<Bgra32, float4>("path-to-source-image");
// This is convolution operation and it cannot be done in-place so we need to create result buffer first
using var destBuffer = device.AllocateReadWriteTexture2D<Bgra32, float4>(imgSource.Width, imgSource.Height);

device.For(imgSource.Width, imgSource.Height, new SobelFilter(imgSource, destBuffer, false, false));

destBuffer.Save("path-to-saved-image");

[AutoConstructor]
public readonly partial struct SobelFilter : IComputeShader
{
    private readonly IReadWriteNormalizedTexture2D<float4> _sourceTexture;
    private readonly IReadWriteNormalizedTexture2D<float4> _targetBuffer;
    private readonly bool _grayscale;
    private readonly bool _invert;

    public void Execute()
    {
        var xy = ThreadIds.XY;

        var top = _sourceTexture[xy + new Int2(0, 1)].RGB;
        var bottom = _sourceTexture[xy + new Int2(0, -1)].RGB;
        
        var topRight = _sourceTexture[xy + new Int2(1, 1)].RGB;
        var middleRight = _sourceTexture[xy + new Int2(1, 0)].RGB;
        var bottomRight = _sourceTexture[xy + new Int2(1, -1)].RGB;
            
        var topLeft = _sourceTexture[xy + new Int2(-1, 1)].RGB;
        var middleLeft = _sourceTexture[xy + new Int2(-1, 0)].RGB;
        var bottomLeft = _sourceTexture[xy + new Int2(-1, -1)].RGB;
        
        var gx = topRight + bottomRight - topLeft - bottomLeft + 2 * (middleRight - middleLeft);
        var gy = topLeft + topRight - bottomLeft - bottomRight + 2 * (top - bottom);
        
        var gradient = Hlsl.Sqrt(gx * gx + gy * gy);

        if (_invert)
        {
            gradient = 1 - gradient;
        }

        if (_grayscale)
        {
            gradient = Hlsl.Dot(gradient, new Float3(0.0722f, 0.7152f, 0.2126f));
        }

        _targetBuffer[xy].RGB = gradient.RGB;
    }
}
```

### Expected Behavior

Because both `_grayscale` and `_invert` captured variables are set to false - we should get colored image with edges defined by light colors like the following:
![2](https://user-images.githubusercontent.com/38229504/187095154-9f72d7c5-6e57-4cf9-80a5-f99047830aec.jpg)

### Actual Behavior

I get grayscaled image with inverted edge colors despite passed bool values `(false, false)` :
![2](https://user-images.githubusercontent.com/38229504/187095189-ffeeac7f-fdec-4082-a012-325e99cb9e97.jpg)

### System info

- **ComputeSharp** NuGet version: 2.0.0-alpha.27
- Operating system version: Windows 10 build 19044.1889
- CPU/GPU model: NVIDIA GeForce GTX 1050 (laptop)
- .NET SDK/runtime version: 6.0.303

### Additional context (optional)

If I use only one captured bool variable, it works as expected.

**Comment by Sergio0694** [comment]
Hey there! Thank you for the kind words, glad to hear you like the library! 😄

This issue seems related to (possibly duplicate of) #193, which I recently fixed in #365. Could you try using the latest build from the preview feed (that fix isn't on the official NuGet package yet) and see if it works correctly now? There were a few issues with marshalling `bool` values in compute shaders, which seems pretty much what's going on here 🙂

See the wiki here for preview packages: [Preview packages 🌙](https://github.com/Sergio0694/ComputeSharp/wiki/2.-NuGet-packages-%F0%9F%93%A6#preview-packages-).

**Comment by KeterSCP** [comment]
Hi! Thanks for the fast response! I tried installing latest build `2.0.9876-foobar.872` from mentioned feed but the issue is unfortunately still there.

**Comment by KeterSCP** [comment]
Oh sorry, it seems like `2.0.9876-foobar.872` isn't the latest build. Now I checked this on `2.0.0-alpha.2944442253` and it indeed was fixed. Thanks for the help!

**Comment by Sergio0694** [comment]
> "2.0.9876-foobar.872"

Yeah sorry that's a test one I accidentally pushed months ago, I should really delete it at some point 🤣

> "Now I checked this on `2.0.0-alpha.2944442253` and it indeed was fixed. Thanks for the help!"

Awesome! Glad to hear that PR did fix this issue as well, thank you for letting me know! 🙂
