### ISSUE TITLE
Cannot capture top level statements delegates

### ISSUE THREAD

**Issue by KeterSCP** [Sergio0694/ComputeSharp#374]
### Reproduction Steps

Run following code sample uncommenting one of the commented lines:

```c#
using ComputeSharp;

using var device = GraphicsDevice.GetDefault();
using var buffer = device.AllocateReadWriteTexture2D<float4>(100, 100);

// device.For(buffer.Width, buffer.Height, new ApplyFunctionShader(buffer, ShaderMethods.AddHalf)); // <-- this works
// device.For(buffer.Width, buffer.Height, new ApplyFunctionShader(buffer, AddHalf)); // <-- this doesn't

[ShaderMethod]
static float4 AddHalf(float4 input) => input + 0.5f;

[AutoConstructor]
public readonly partial struct ApplyFunctionShader : IComputeShader
{
    private readonly ReadWriteTexture2D<float4> _sourceTexture;
    private readonly Func<float4, float4> _func;
    
    public void Execute()
    {
        _sourceTexture[ThreadIds.XY] = _func(_sourceTexture[ThreadIds.XY]);
    }
}

public static class ShaderMethods
{
    [ShaderMethod]
    public static float4 AddHalf(float4 input) => input + 0.5f;
}
```

### Expected Behavior

In both cases delegate is captured and shader is properly computed.

### Actual Behavior

If capturing top level statements delegate I get an exception
`System.ArgumentException: The captured delegate "_func" was wrapping a method without the [ShaderMethod] attribute applied to it. (Parameter '_func')`

### System info

This section should contain useful info such as:
- **ComputeSharp** NuGet version: 2.0.0-alpha.2985861268
- Operating system version: Windows 10 build 19044.1889
- GPU model: NVIDIA GeForce RTX 3080
- NET SDK/runtime version: 6.0.303

### Additional context (optional)

It is not critical, but it would be nice to have this fixed as using such methods from top level statements simplify testing

**Comment by Sergio0694** [comment]
This happens because in the first case Roslyn creates a `LocalFunctionStatementSyntax`, not a `MethodDeclarationSyntax`. As such, the generator looking for methods with `[ShaderMethod]` on them won't find that. This should be fixable with some tweaks.
