### ISSUE TITLE
GitHub packages CI step failing

### ISSUE THREAD

**Issue by Sergio0694** [Sergio0694/ComputeSharp#403]
### Description

The CI step to push to GitHub packages started failing, for some reason:

```
Pushing ComputeSharp.Pix.2.0.0-alpha.3242075036+6131b7f9b0d2ee95c98e5e76a5f5bafe62ef74ae.nupkg to 'https://nuget.pkg.github.com/ComputeSharp'...
  PUT https://nuget.pkg.github.com/ComputeSharp/
warn : Source owner 'ComputeSharp' does not match repo owner 'Sergio0694' in repository element.
  BadRequest https://nuget.pkg.github.com/ComputeSharp/ 380ms
error: Response status code does not indicate success: 400 (Bad Request).
```

Eg. see https://github.com/Sergio0694/ComputeSharp/actions/runs/3242075036.

There have been no recent changes to the CI script or the package info recently, so not sure what's up with this.

@nirmal4g are you familiar with this by any chance? I'm not sure I understand what the issue is 😅

**Comment by Nirmal4G** [comment]
@Sergio0694 It could be because of this: <https://github.blog/changelog/2022-10-10-packages-consolidated-owner-and-admin-role>

**Comment by Sergio0694** [comment]
Mmmh yeah that seems related. I'm not seeing an explanation on how to fix existing workflows though 🤦‍♂️

**Comment by Nirmal4G** [comment]
This couldn't be NuGet issue but rather issue with GitHub NuGet hosting related to the owner consolidation change. I think you should report it to the GitHub Actions and Packages team.

**Comment by Nirmal4G** [comment]
I'm just thinking out loud here, maybe creating a new token could be a fix/workaround!?

**Comment by Sergio0694** [comment]
I'm thinking maybe it'd be better to just skip that step for now until this is fixed. All nightlies are already pushed to the ADO feed anyway, which is also probably better either way because it doesn't force users to be logged through GitHub to use it 🤔
