### ISSUE TITLE
APIs to get the shader profile and compile options for a shader

### ISSUE THREAD

**Issue by Sergio0694** [Sergio0694/ComputeSharp#411]
### Description

Currently, there's no way to check the shader profile and compile options for a shader programmatically.
This information is available, just not exposed. There should be new APIs to get this when loading bytecode.
This would also get parity with other shader info, as it's the only bit of info that can't be retrieved.

### Proposed API

```csharp
namespace ComputeSharp.D2D1.Interop;

public static class D2D1PixelShader
{
    public static ReadOnlyMemory<byte> LoadBytecode<T>(out D2D1ShaderProfile shaderProfile, out D2D1CompileOptions options)
        where T : unmanaged, ID2D1PixelShader;

    public static ReadOnlyMemory<byte> LoadBytecode<T>(D2D1ShaderProfile shaderProfile, out D2D1CompileOptions options)
        where T : unmanaged, ID2D1PixelShader;

    public static ReadOnlyMemory<byte> LoadBytecode<T>(D2D1CompileOptions options, out D2D1ShaderProfile shaderProfile)
        where T : unmanaged, ID2D1PixelShader;
}
```

This change is needed in the private `ID2D1Shader` interface:

```diff
namespace ComputeSharp.D2D1.__Internals;

public interface ID2D1Shader
{
-   void LoadBytecode<TLoader>(ref TLoader loader, D2D1ShaderProfile? shaderProfile, D2D1CompileOptions? options)
-       where TLoader : struct, ID2D1BytecodeLoader;

+   void LoadBytecode<TLoader>(ref TLoader loader, ref D2D1ShaderProfile? shaderProfile, ref D2D1CompileOptions? options)
+       where TLoader : struct, ID2D1BytecodeLoader;
}
```

cc. @rickbrew

**Comment by rickbrew** [comment]
This is a fairly clumsy, weird API ... nullable `ref` parameters for the private API, and 3 overloads for the public one? I would expect a simpler input/output model. Have a struct passed in with the optional profile and options, and then a struct that comes out with the actual/effective profile and options. This also makes it so that if/when you want to add new fields you won't need to revise the method to add more parameters.

**Comment by Sergio0694** [comment]
Yeah it's a bit awkward, but I'm not really concerned about the private interface (since it's private), and for the public one, there really are no more options I can imagine adding to this, and I don't want to add some new public type so close to the first release (both because I wouldn't know how to name it, but also because I don't want to make such a big change now). Adding these overloads is pretty harmless, and has no breaking changes on any existing user 🙂

Also, found a bug causing the wrong shader profile and options to be used in some cases, fixed it while working on this 😄
