### ISSUE TITLE
Extended support for custom D2D1 transform mappers

### ISSUE THREAD

**Issue by Sergio0694** [Sergio0694/ComputeSharp#420]
### Description

While working on `PixelShaderEffect<T>` (see #417) and talking with @rickbrew on future improvements, it became clear that it would be useful to extend the built-in `ID2D1Effect` in ComputeSharp.D2D1 to allow passing arbitrary stateful transform mappers. That is, along with the existing support for configuring a transform mapper factory when registering the effect, there will also be a way to assign custom transform mappers onto existing effects. Along with this, the transform mappers will have the ability of modifying the constant buffer of the shader in their `MapInputsToOutput` call. This enables advanced effects that need to access the dispatch size to work automatically, without the need for consumers to pass the dispatch size as input. This is crucial especially for allowing packaging easier to use, Win2D-compatible effects. As such, this proposal needs to modify several components in ComputeSharp.D2D1.

### Proposed API

First, the following types will be removed entirely:
- `ID2D1TransformMapper<T>`
- `ID2D1TransformMapperFactory<T>`
- Associated APIs in eg. `D2D1PixelShaderEffect` and other types

Then, the following APIs will be added:

```csharp
namespace ComputeSharp.D2D1.Interop;

public abstract class D2D1TransformMapper<T> : ICustomQueryInterface
    where T : unmanaged, ID2D1PixelShader
{
    public abstract void MapInputsToOutput(
        D2D1DrawInfoUpdateContext<T> drawInfoUpdateContext,
        ReadOnlySpan<Rectangle> inputs,
        ReadOnlySpan<Rectangle> opaqueInputs,
        out Rectangle output,
        out Rectangle opaqueOutput);

    public abstract void MapOutputToInputs(
        in Rectangle output,
        Span<Rectangle> inputs);

    public abstract void MapInvalidOutput(
        int inputIndex,
        Rectangle invalidInput,
        out Rectangle invalidOutput);

    CustomQueryInterfaceResult ICustomQueryInterface.GetInterface(ref Guid iid, out IntPtr ppv);
}

public static class D2D1TransformMapperFactory<T>
    where T : unmanaged, ID2D1PixelShader
{
    public static D2D1TransformMapper<T> Inflate(int amount);
    public static D2D1TransformMapper<T> Inflate(int left, int top, int right, int bottom);
    public static D2D1TransformMapper<T> Inflate(Accessor<int> accessor);
    public static D2D1TransformMapper<T> Inflate(Accessor<(int Left, int Top, int Right, int Bottom)> accessor);
    public static D2D1TransformMapper<T> Transform(Matrix3x2 matrix);
    public static D2D1TransformMapper<T> Transform(Accessor<Matrix3x2> accessor);

    public delegate TResult Accessor<TResult>(in T shader);
}

public readonly ref struct D2D1DrawInfoUpdateContext<T>
    where T : unmanaged, ID2D1PixelShader
{
    public T GetConstantBuffer();
    public void SetConstantBuffer(in T shader);
}
```

In particular, `D2D1TransformMapper<T>` acts as an equivalent for `D2D1ResourceTextureManager`: it natively supports getting a CCW out of it, and it can be implemented to support custom transform mappings that can interoperate with the built-in effect. To support all of this this, the following COM interfaces will be added (mirroring [ID2D1DrawTransform](https://learn.microsoft.com/en-us/windows/win32/api/d2d1effectauthor/nn-d2d1effectauthor-id2d1drawtransform)):

```cpp
[uuid(430C5B40-AE16-485F-90E6-4FA4915144B6)]
interface ID2D1DrawInfoUpdateContex : IUnknown
{
    HRESULT GetConstantBufferSize([out] UINT32 *size);

    HRESULT GetConstantBuffer(
        [out] BYTE   *buffer,
              UINT32 bufferCount);

    HRESULT SetConstantBuffer(
        [in] const BYTE *buffer,
             UINT32     bufferCount);
}

[uuid(02E6D48D-B892-4FBC-AA54-119203BAB802)]
interface ID2D1TransformMapper : IUnknown
{
    HRESULT MapInputRectsToOutputRect(
        [in]  const ID2D1DrawInfoUpdateContex *updateContext,
        [in]  const RECT                      *inputRects,
        [in]  const RECT                      *inputOpaqueSubRects,
              UINT32                          inputRectCount,
        [out] RECT                            *outputRect,
        [out] RECT                            *outputOpaqueSubRect);

    HRESULT MapOutputRectToInputRects(
        [in]  const RECT *outputRect,
        [out] RECT       *inputRects,
              UINT32     inputRectsCount);

    HRESULT MapInvalidRect(
              UINT32 inputIndex,
              RECT   invalidInputRect,
        [out] RECT*  invalidOutputRect);
};
```

The built-in `ID2D1Effect` will also receive a new property to assign this (of type `IUnknown`):

```diff csharp
namespace ComputeSharp.D2D1.Interop;

public static class D2D1PixelShaderEffectProperty
{
+   public const uint TransformMapper = 17;
}
```

Finally, these additional APIs will be added to bridge the various components together:

```diff csharp
namespace ComputeSharp.D2D1.Interop;

public static class D2D1PixelShaderEffect
{
+   public static void SetTransformMapperForD2D1Effect(void* d2D1Effect, void* transformMapper);
+   public static void SetTransformMapperForD2D1Effect<T>(void* d2D1Effect, D2D1TransformMapper<T> transformMapper)
+       where T : unmanaged, ID2D1PixelShader;
}
```

These two new API allow assigning a given transform mapper to an effect.

### Drawbacks

Extra complexity in general.

### Alternatives

None, this is just enabling new features that aren't possible today.

### Other thoughts

![](https://user-images.githubusercontent.com/10199417/198854564-bbf52665-87eb-4111-96c7-d29b6091a637.png)

**Comment by rickbrew** [comment]
```cs
public readonly ref struct D2D1DrawInfoUpdateContext<T>
    where T : unmanaged, ID2D1PixelShader
{
    public ref T GetConstantBufferReference();
}
```

I feel like this should be a pair of get/set methods. With the `ref` version it's not clear that you can _set_ the buffer's contents _and_ that it will do anything. Having `ref readonly T GetConstantBuffer()` + `void SetConstantBuffer(in T)` makes this much, much clearer. It also just expresses intent in a much clearer, more idiomatic way.

It's also much easier to optimize. You'll know exactly when the const buffer is being set, there's no need to diff it.

**Comment by Sergio0694** [comment]
The rational was that with that API you could do changes in-place if you wanted. Whereas here you'd necessarily have to read the constant buffer to a local (ie. copying it), and then write it back, which means you could copy a potentially large buffer even just to update a single value. Also being able to just assign to fields there seemed nicer than having to copy and reassingn? 🤔

**Comment by rickbrew** [comment]
The buffers aren't actually that large though, and I don't think it's worth the loss in clarity anyway. And most mappers will not be making changes to the shader constants, but if this is a property then you must always perform a diff -- which is, by definition, most expensive when there are no changes.

**Comment by Sergio0694** [comment]
Yeah that's fair. I guess one thing I'm not sure about though is, you have:

```csharp
public readonly ref struct D2D1DrawInfoUpdateContext<T>
    where T : unmanaged, ID2D1PixelShader
{
    public ref readonly T GetConstantBuffer();
    public void SetConstantBuffer(in T shader);
}
```

If you call ○6SetConstantBuffer`, I'd expect the context to update the local copy of the marshalled constant buffer (ie. as a `T` value), and then to update the constant buffer in the underlying `ID2D1DrawInfo`. Now, that local copy would be the same one that `GetConstantBuffer` returns a reference to. In other words, if you get a reference via `GetConstantBuffer`, then call `SetConstantBuffer`, the changes will be reflected in the value you see by reading the shader from that returned reference you already had. Which I guess it's not necessarily bad (`ref readonly` makes no guarantees that the storage is readonly, it only tells you that _your_ reference to that storage is readonly), we just need to document this behavior. Then again I might just be overthinking it - I wouldn't expect people to try to read the buffer again after updating it, since that's likely the last thing they'd do in a transform anyway.

**Comment by rickbrew** [comment]
Then just have it return by-value, `public T GetConstantBuffer();` ¯\_(ツ)_/¯
