### ISSUE TITLE
Is there a plan to support GLSL in the future?

### ISSUE THREAD

**Issue by CeSun** [Sergio0694/ComputeSharp#421]

**Comment by Sergio0694** [comment]
There's no plan for that, no. ComputeSharp uses D3D12/D2D as backend, so it's strictly tied to HLSL because of this, and there are no plans to add different or multiple backends in the future 🙂

**Comment by hawkerm** [comment]
@Sergio0694 can we posit this from a different angle? I thought I remember you saying that the resulting hlsl file gets outputted as part of the source generator, right?

Like if the execution of the code on the hardware is abstracted, ultimately the C# source generator translates the C# code to the shader instructions in hlsl, right? Thinking mostly for pixel shaders here where GLSL is used in other multi-platform game engines over HLSL. [Godot for instance uses a superset/subset/variation of GLSL](https://docs.godotengine.org/en/stable/tutorials/shaders/converting_glsl_to_godot_shaders.html#doc-converting-glsl-to-godot-shaders)...

Would it be possible to at least then generate a translated version of the resulting GLSL code from the C#? (Though I know there needs to be accounting for the alternate coordinate system and base functions.) So, maybe a direct transpilation isn't feasible, but maybe there could be an alternate attribute and helpers for at least generation glsl from C# code, so it can be run elsewhere in the workflow as part of something external to ComputeSharp, but at least the shader code can remain in something more familiar to a C# developer?

It seems like some of the HLSL generation is abstracted in `ComputeSharp.SourceGeneration.Hlsl` or do I misunderstand its purpose?

Just a thought that could broaden the appeal of using C# for shader code not directly tied to HLSL? Another thought for a 3.0, maybe? 😅
