### ISSUE TITLE
Single Namespace for UI Controls across UWP/WindowsAppSDK

### ISSUE THREAD

**Issue by hawkerm** [Sergio0694/ComputeSharp#442]
### Description (optional)

The controls should be under a single unified namespace like `ComputeSharp.WinUI`, see here:

https://github.com/Sergio0694/ComputeSharp/blob/f0b0edf516e807bee1bad3b36b02516f1c616091/src/ComputeSharp.UI/Controls/ComputeShaderPanel.cs#L12-L16

### Rationale

With separate namespaces it means you have to have different XAML xmlns declarations to use them and thus can't share the same XAML file between a UWP app and a Windows App SDK app, this makes testing migration and porting more difficult (as you've seen with having to duplicate the XAML code with the samples).

The Windows Community Toolkit has this same issue, which is being addressed in their next release, see https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4488

### Proposed API

Namespace for XAML controls should be aligned to `ComputeSharp.WinUI`.

### Drawbacks

Slightly confusing with different package names which don't match the namespace, but I believe benefit outweighs this.

### Alternatives

🤷‍♂️

**Comment by hawkerm** [comment]
@Sergio0694 do you have plans for a 3.0 in the future where a breaking change like this would work? Think could help simplify some of the codebase to adopt what was done in the Windows Community Toolkit with global usings and unified namespaces?

**Comment by Sergio0694** [comment]
Closing this, since UWP support is not present anymore (was removed in #602) 🥲
