### ISSUE TITLE
Possibility of supporting C# 7.3 for UWP projects?

### ISSUE THREAD

**Issue by LancerComet** [Sergio0694/ComputeSharp#443]
It seems like ComputeSharp requires C# 10 to fire up but only C# 7.3 is available for UWP projects.
Is it possible to make ComputeSharp generate C# 7 codes? Many thanks

![c-sharp-10-required](https://user-images.githubusercontent.com/10321350/205353026-8b571782-11b2-4d44-a4eb-0dcb5f6e7d68.png)

**Comment by Sergio0694** [comment]
> "only C# 7.3 is available for UWP projects"

That is not true, you can use C# 10 just fine 🙂
Just add this to your .csproj:

```csharp
<LangVersion>10.0</LangVersion>
```

You'll notice I already have a few UWP projects in the repo (as well as the sample app) and they do the same as well 😄
