### ISSUE TITLE
Plans to make it cross platform?

### ISSUE THREAD

**Issue by wubalubadubdub55** [Sergio0694/ComputeSharp#446]
Just found about this project. Very interesting!

Can you please make it cross platform so we could run this in Apple Silicon for example?

Thanks!

**Comment by Sergio0694** [comment]
Hey there! There are no plans for this at the moment, ComputeSharp is tightly coupled with DirectX 12 and Direct2D 🙂
It's possible to get ComputeSharp running on Vulkan, but it requires significant work (I know there's a fork out there with this).
