### ISSUE TITLE
How do I profile my compute shader?

### ISSUE THREAD

**Issue by MyNameIsTrez** [Sergio0694/ComputeSharp#452]
# Intro
I'm new to C# and ComputeSharp but have been able to cobble together a crummy console program in Visual Studio that essentially sorts the colors of an input image. I've got it working, but it's really slow, and the point of this project for me was to learn how to optimize a compute shader, but I'm kind of stuck. I know of a few tricks like replacing if-statements with branchless programming, but I don't want to blindly change stuff without having profiling statistics to back it all up.

https://user-images.githubusercontent.com/32989873/207989595-ef8dee15-b65b-460a-a1aa-a7f1378e4bd0.mp4

# My program
[The source code](https://github.com/MyNameIsTrez/Color-Sorting/blob/master/2d/gpu-swap/Color-Sorting/Color-Sorting/Program.cs).

A 1D array of numbers is trivial to sort, but a 2D image of pixels less so. The simplest idea that I had for sorting the colors of an image is randomly swapping pixels, and reverting the swap if it made the image uglier.

I had to create some sort of metric for determining prettiness, so the score of a pixel is the sum of the differences to its eight neighboring pixels: If you imagine that there's a red pixel surrounded by eight neighbors that are also red then the score will be low, while a red pixel surrounded by eight blue neighbors will have a high score.

Note that taking the RGB difference of two colors is really inaccurate, since a difference of say 42 on the red channel will wildly vary from not being noticeable at all to being very noticeable depending on the RGB values involved. This is why the RGB colors are first translated to CIELAB color space.

# What I've tried
In Visual Studio I've installed the ComputeSharp, ComputeSharp.Dynamic and ComputeSharp.Pix NuGets.
I can't find any documentation for ComputeSharp.Pix usage, but its description reads "An extension library for ComputeSharp to enable PIX support to produce debugging information", so I figure it's probably what I am looking for, but I don't know how to use it.

I've downloaded PIX on Windows and let it launch my Debug build, and while it does seem to recognize when the compute shader code starts to run since its "GPU Capture" button lights up at that moment, I'm not seeing any profiling results at the end:

https://user-images.githubusercontent.com/32989873/207988771-0e8e45dc-3be4-47e2-8517-876b23e0e579.mp4

Ideally I wouldn't even need to use an external program like PIX and would see the performance stats within Visual Studio next to the line numbers, but I can't figure out how I can get *any* profiling to work at all, so any advice is highly appreciated! Feel free to look at the ugly C# code I linked above. :)

**Comment by electro-logic** [comment]
Hello, have you tried to attach PIX to your process and to click on GPU Capture?
Please have a look here https://www.youtube.com/watch?v=UH-o5cG_QWo for a PIX introduction

**Comment by Sergio0694** [comment]
Closing this since it's not an actual issue with the library. I recommend reading up on the docs on how to use PIX like @electro-logic also suggested. I've specifically created `ComputeSharp.Pix` to make that kind of scenario possible 🙂

Thank you!
