### ISSUE TITLE
Helper APIs to load D2D1ResourceTextureManager-s from images

### ISSUE THREAD

**Issue by Sergio0694** [Sergio0694/ComputeSharp#463]
### Description

It is not straightforward to get a `D2D1ResourceTextureManager` instance from an image file, as consumers are expected to handle loading the file and doing all appropriate conversions to obtain the decoded raw pixel buffer, and then use it to construct a manager with the necessary padding/format/depth/strides values as well. This is not trivial and can be error prone, and at the very least it means there's considerable amount of extra code that's necessary to use these APIs. We should add helpers to make this easier.

### Proposed API

This first proposal targets the most common scenarios, loading images with RGBA32, straight alpha format by default:

```csharp
namespace ComputeSharp.D2D1.Interop;

public sealed unsafe class D2D1ResourceTextureManager : ICustomQueryInterface
{
    public static D2D1ResourceTextureManager LoadImage(string filename);
    public static D2D1ResourceTextureManager LoadImage(ReadOnlySpan<char> filename);
    public static D2D1ResourceTextureManager LoadImage(ReadOnlySpan<byte> span);
    public static D2D1ResourceTextureManager LoadImage(Stream stream);
}
```

Additional overloads taking extra parameters to control the decoding can then be added later on if needed.

### Alternatives

Do nothing, but then using these APIs will remain a bit cumbersome.

### Other thoughts

The logic is pretty much the same in ComputeSharp proper, just adapted and ported to the D2D1 package as well.
Images greater than 16,384 pixels in either dimensions are not supported, and will result in an exception.

**Comment by rickbrew** [comment]
What about helpers to initialize from an `IWICBitmapSource` ?

**Comment by Sergio0694** [comment]
Talked with @rickbrew offline (I mean on Discord), shelving this for now.
