### ISSUE TITLE
Missing `mad instruction from `Hlsl`

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#477]
`mad` seems to be missing? https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/mad

It calculates `m * a + b`. Similar to `fma`, but `fma` is for `double` and friends only. Not sure why they split it up like that.

I have need of this in some of my shaders since it can be faster to do `mad(m, a, b)` than `m * a + b`.

**Comment by Sergio0694** [comment]
Forgot to link the issue, this is implemented now 😄
