### ISSUE TITLE
Instance methods cannot call methods in other structs

### ISSUE THREAD

**Issue by Avid29** [Sergio0694/ComputeSharp#479]
### Description (optional)

Instance methods belonging to non-shader structs are not able to call instance or static methods belonging to other structs.

### Reproduction Steps

The following code will reproduce the error:

```cs
[AutoConstructor]
[EmbeddedBytecode(DispatchAxis.XY)]
public readonly partial struct Shader : IComputeShader
{
    private readonly IReadWriteNormalizedTexture2D<float4> _texture;
    
    public void Execute()
    {
        Foo foo;
        foo.InstanceMethodTest();
        foo.StaticMethodTest();
    }
}

public struct Foo
{
    public void InstanceMethodTest()
    {
        Bar bar;
        bar.InstanceMethod();
    }

    public void StaticMethodTest()
    {
        Bar bar;
        bar.StaticMethod();
    }
}

public struct Bar
{
    public void InstanceMethod()
    {
    }

    public static void StaticMethod()
    {
    }
}
```

### Expected Behavior

The code should compile and run, calling the method as expected.

### Actual Behavior

Error ``CMPS0046``.

It appears the HLSL generator cannot find the method belonging to the other struct.

### System info

- ComputeSharp 2.0.3
- 22H2 (22621.1105)
- i7-8550U CPU
- Visual Studio Community 17.4.4
- .net7-windows

### Additional context (optional)

Any additional info that might be useful to resolve the issue.

**Comment by rickbrew** [comment]
@Sergio0694 I thought this was fixed awhile ago? We just had a conversation about it like a week ago :)

**Comment by Sergio0694** [comment]
Not sure I'm entirely following here. The repro code above has this:

```csharp
bar.StaticMethod();
```

But that's... Not valid syntax at all? 😅

That said I can double check some scenarios of calling methods from different structs back and forth and add some tests, sure. It's quite possible I did miss some edge case there maybe when calling things from one place to the other, I'll look into it.

**Comment by Sergio0694** [comment]
Ok so there's two issues here that the HLSL rewriter needs to solve to make this work:
- Forward declarations for struct types
- Forward declarations for instance methods on struct types

Without those two, the code won't compile because the types are not fully defined yet. Minimal repro:

```csharp
[EmbeddedBytecode(DispatchAxis.X)]
[GeneratedComputeShaderDescriptor]
public readonly partial struct Shader(ReadWriteBuffer<int> buffer) : IComputeShader
{    
    public void Execute()
    {
        Foo foo = default;
        Baz baz = default;

        foo.Bar(baz);
    }
}

public struct Foo
{
    public void Bar(Baz baz)
    {
        baz.Blah();
    }
}

public struct Baz
{
    public void Blah()
    {
    }
}
```
