### ISSUE TITLE
Using ComputeSharp/GPGPU to find roots of thousands of transformation-functions

### ISSUE THREAD

**Issue by alexander802** [Sergio0694/ComputeSharp#503]
I am currently thinking about using ComputeSharp to speed up my algorithm which is really heavy in terms of computation and amount of data, and also has time-constraints. I need a solution within 4-5 seconds otherwise the result is not valid anymore.

If I am not mistaken, the whole advantage of processing data in the GPU is when there is one or little "transformation-function/s" that transforms a lot of input-data to a lot of output-data in parallel!?

But in my case it's different: I have ten-thousands of different transformation-functions that are also created dynamically at runtime. With this functions I have to find the appropriate roots via numeric interpolation. I wanted to do this task with the GPU to speedup things.

```
Func<double, double> function1 = ...
Func<double, double> function2 = ...
...
Func<double, double> function120000 = ...
```

Is something like that achievable with GPGPU and in particular ComputeSharp?

**Comment by Sergio0694** [comment]
> "I have ten-thousands of different transformation-functions that are also created dynamically at runtime"

Unfortunately that's not a scenario that ComputeSharp supports. The way ComputeSharp works is that it bundles a source generator that inspects the shader code and generates all supporting code for it (the transpiled HLSL source, the compiled bytecode, etc.). If you're dynamically generating code at runtime, there is no way for those source generators to see and process all of that. ComputeSharp can only work with source that is available at compile time 🙂
