### ISSUE TITLE
The GPU device instance has been suspended

### ISSUE THREAD

**Issue by miyconst** [Sergio0694/ComputeSharp#51]
Hi, I am playing around with your library and wanted to compare performance of two of my GPUs.

For this I am doing the following:

```cs
List<GraphicsDevice> gpus = Gpu.EnumerateDevices().ToList();

for (int g = 0; g < gpus.Count; g++)
{
    Stopwatch stopwatch = new Stopwatch();
    
    stopwatch.Start();
    this.DoComputation(gpus[g]);
    stopwatch.Stop();

    Console.WriteLine($"GPU {g}: {stopwatch.Elapsed}.");
}
```

But I am getting the following error:

```
Unhandled exception. SharpGen.Runtime.SharpGenException: HRESULT: [0x887A0005], Module: [Vortice.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

   at SharpGen.Runtime.Result.CheckError()
   at Vortice.Direct3D12.ID3D12Device.CreateCommittedResource(HeapProperties& heapPropertiesRef, HeapFlags heapFlags, ResourceDescription& descRef, ResourceStates initialResourceState, Nullable`1 optimizedClearValueRef, Guid riidResource)
   at Vortice.Direct3D12.ID3D12Device.CreateCommittedResource(HeapProperties heapProperties, HeapFlags heapFlags, ResourceDescription description, ResourceStates initialResourceState, Nullable`1 optimizedClearValue)
   at ComputeSharp.Graphics.Buffers.Buffer`1..ctor(GraphicsDevice device, Int32 size, Int32 sizeInBytes, BufferType bufferType)
   at ComputeSharp.Graphics.Buffers.Abstract.HlslStructuredBuffer`1.GetData(Span`1 span, Int32 offset, Int32 count)
   at ComputeSharp.Graphics.Buffers.Abstract.HlslBuffer`1.GetData(Int32 offset, Int32 count)
   at ComputeSharp.Graphics.Buffers.Abstract.HlslBuffer`1.GetData()
```

I know it's an issue in the DirectX, but maybe you know how to solve it?

The same code works with `Gpu.Default`.

Also, is it possible to retrieve any info about the GPU? Like name, vRAM size, cores count?

---------

My setup:

- Visual Studio 2019.
- .NET Core `3.0.0-preview8-28405-07`.
- GTX 1080.
- GTX 1050 ti.
- Windows 10 Pro x64.

**Comment by Sergio0694** [comment]
Hi, thank you for your feedback!
Could you share the full code snippet, including the code in `DoComputation`, so that I can test it out locally? Also, if you clone the `master` and try to run one of the samples (eg. the `ImageProcessing` sample), do they work fine for you?

**Comment by miyconst** [comment]
Wow! Thanks for such a fast reply.

Here is entire gist of my application - [AccelerationGraph.cs](https://gist.github.com/miyconst/92aef9a4917897dbb28cb6eb94019c95).

To reproduce the issue, you need to replace:

```cs
// List<GraphicsDevice> gpus = Gpu.EnumerateDevices().ToList();
List<GraphicsDevice> gpus = new List<GraphicsDevice>() { Gpu.Default };
```

With:

```cs
List<GraphicsDevice> gpus = Gpu.EnumerateDevices().ToList();
// List<GraphicsDevice> gpus = new List<GraphicsDevice>() { Gpu.Default };
```

Let me try to clone and run the samples.

**Comment by Sergio0694** [comment]
@miyconst Nevermind, found the issue from your gist 👍
You were always allocating the buffers from the default device even when you were targeting another.

See here: https://gist.github.com/miyconst/92aef9a4917897dbb28cb6eb94019c95#file-accelerationgraph-cs-L41

A buffer is tied to a specifid GPU, so there you need to replace `Gpu.Default.Allocate...` with `gpu.Allocate...`

**Comment by miyconst** [comment]
>A buffer is tied to a specifid GPU ...

Aha, got it. Thanks a lot!

>**EDIT**: also, I've updated some APIs to expose the info you requested (eg. total cores, GPU memory), I'll include them in the next update 😄

That's very welcome :).

**Comment by Sergio0694** [comment]
No problem, happy to help! Glad we could get this fixed so quickly 😊

**Comment by miyconst** [comment]
Do you think it would be reasonable to add some kind of more meaningful exception message?

**Comment by Sergio0694** [comment]
I might give it a shot, sure!

Also, small note: you should preload the shader outside of your benchmark. The first time you run a shader, the lib has to convert it to HLSL and compile it, which takes some time. After that, it reads it from an internal cache. I've run your benchmark and the GPU time went down from over 2s to 0.5s by preloading the kernel. By preloading I mean, just run the whole method once and discard the results.

The performance delta with the CPU can also vary a lot depending on the workload. For instance, the bokeh blur example in one of the samples, when put against a CPU implementation, runs over 25x faster (I did my tests with a Ryzen 7 2700X and a GTX1080).

**Comment by miyconst** [comment]
>... you should preload the shader outside of your benchmark.

Yeah, I have already figured that out. I was looking for something similar to "Prepared statements" in SQL databases, but could not find it, thus I just run the function with a small buffer.

------

My case is some kind of data analysis from an input sensor, which gives me the following:

- For 2 hours, with 60 values per second.
- Threadripper 1950x: `0.21s`.
- GTX 1080: `0.0055s`, ~40x better.
- GTX 1050 ti: `0.0105s`, ~20x better.

So, the performance is notably better on GPUs.

**Comment by Sergio0694** [comment]
Yeah you can just run the shader with 1 iteration, that works too 👍
The important thing is just that the number of iteration axes remains the same during your preloading and actual iteration. That's the same reason why I haven't added an API to preload a shader, as a shader also contains the number of threads to run along each axis (the `ThreadNum` HLSL attribute).
Basically, you can do this:
- If your shader will be run just on the X axis, preload it with `1`
- If it'll run on X and Y, preload it with `2`, `2`
- If it'll run on X, Y and Z, preload it with `2`, `2`, `2`

As for your results, glad to hear you're having such an improvement in your scenario! 🚀
If you want to squeeze out even more performance, you can also try to tweak the shader, eg. to process more than one output value in each iteration, so that the relative overhead for each value would be reduced. You'll need to make some tests for this though, as results may vary depending on your specific input data, buffer size, etc. - but it might be worth a try if you want the best possible performance.

**Comment by Sergio0694** [comment]
Hey @miyconst - just a small update. I've pushed out a new package (version `1.2.1`) that includes both those new properties for the `GraphicsDevice` class (the number of compute units and the device name), and a new custom exception when you use invalid buffers in a shader, that specifically details what device has been used to allocate the buffers and to run the shader.

Hope this helps! 👍

**Comment by miyconst** [comment]
Thanks a lot @Sergio0694!
