### ISSUE TITLE
cudaMemset equivalent

### ISSUE THREAD

**Issue by ImmaB** [Sergio0694/ComputeSharp#547]
I am currently migrating a Cuda Codebase to ComputeSharp and I cannot find an equivalent to the cudaMemset function. It works like the C memset function but writes directly to GPU memory.
I know this can be achieved with copying from CPU to GPU Memory or a Shader as well but apparently the cudaMemset function works in a more performant way. Maybe this is already possible, and I just can't find it.

**Comment by Sergio0694** [comment]
Hi there! This is not possible, as DX12 has a very different memory model than CUDA's unified memory. If you need a very efficient approach to copying memory, you'll have to just leverage upload/readback buffers, to minimize/avoid copying when not necessary, but you cannot avoid explicitly copying data from there to actual GPU buffers, as those are physically different 🙂
