### ISSUE TITLE
Support for generics in shader types not implemented?

### ISSUE THREAD

**Issue by Kloizdena** [Sergio0694/ComputeSharp#548]
### Description (optional)

I'm trying to write a generic shader that I could reuse with multiple different parameter types. I created a generic struct to support my scenario, but when I try to build it, code generation fails.

### Reproduction Steps

The outline of the shader is similar to this:

```csharp
[AutoConstructor]
public readonly partial struct GenericShader<T> : IPixelShader<float4>
    where T : struct
{
    private readonly T initialParams;
    private readonly int iterations;
    private readonly Func<T, int, T> generate;
    private readonly Func<T, int, float4> getColor;

    public float4 Execute()
    {
        var p = initialParams;
        for (int i = 0; i < iterations; i++)
        {
            p = generate(p, i);
        }
        return getColor(p, iterations);
    }
}
```

A dummy example to use this shader could be the following:

```csharp
var shader = new GenericShader<Param1>(
    initialParams: new Param1 { X = 1, },
    iterations: 10,
    generate: Generate,
    getColor: GetColor
    );
// ... run shader

[ShaderMethod]
static Param1 Generate(Param1 param, int i)
{
    param.X = i;
    return param;
}

[ShaderMethod]
static float4 GetColor(Param1 param, int i)
{
    return param.X;
}

struct Param1
{
    public float X;
}

```

### Expected Behavior

The code generator should generate code without error.

### Actual Behavior

The output shows a warning and code is not generated for my shader:

1>CSC : warning CS8785: Generator 'IShaderGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.TypeParameterSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'

### System info

This section should contain useful info such as:
- **ComputeSharp.Dynamic** NuGet version: 2.0.3
- Operating system version: Microsoft Windows [Version 10.0.22621.2134]
- CPU/GPU model (the latter is especially useful for shader issues): AMD Ryzen 7 5825U
- Visual Studio version Version 17.7.0, .NET SDK version 7.0.400

**Comment by Sergio0694** [comment]
Generic shaders are not supported, so this not working is the expected behavior. Of course, the generator shouldn't just fail like that though. I've added some new checks in #686 to prevent this and make the scenario just fail gracefully 🙂
