### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [Sergio0694/ComputeSharp#561]
Maybe You will be interested in hosting API Explorer online:

https://www.robiniadocs.com/d/computesharp/api/ComputeSharp.html

This is ready-to-go, so above link can be added to README for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/computesharp/api/ComputeSharp.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/computesharp/api/ComputeSharp.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

**Comment by Sergio0694** [comment]
Thank you for that showcase! This is not something I plan on supporting though, as I can't really justify the additional complexity for that when all the same info for XML docs is already available via https://source.computesharp.dev/ as well 🙂
