### ISSUE TITLE
System.NotSupportedException: 

### ISSUE THREAD

**Issue by ElAmen** [Sergio0694/ComputeSharp#60]
There isn't a supported GPU device on the current machine'.

Please am running into this issue.
My machine has NVIDIA GPU.

**Comment by Sergio0694** [comment]
Hi, what GPU device do you have on your machine? `ComputeSharp` needs a GPU with DX12.1 support to be able to run properly.

**Comment by ElAmen** [comment]
NVIDIA GeForce GT 750M
DirectX 12

**Comment by Sergio0694** [comment]
Ah, that explains it. The GT750M didn't originally support DX12 (it was released in 2013, see [here](https://laptopmedia.com/video-card/nvidia-geforce-gt-750m-4gb-ddr3/)) and even with new driver updates it just doesn't support DX12.1 and other newer features, which are required by `ComputeSharp`.

So I'd say that's not an issue, unfortunately your GPU just doesn't support the necessary requirements that are needed to properly run this library.
