### ISSUE TITLE
How to render a texture within a specific area of a Win32 window?

### ISSUE THREAD

**Issue by PandrPi** [Sergio0694/ComputeSharp#616]
Hello,
I'm using swap chain sample project to gather some experience about ecosystem ans so on.

However, I'm stuck at the stage where I need to render the texture not for the entire window but only within a little rect of the window, so that both the title bar and the texture rendering will actually work.

I'm almost sure that I need to modify Win32Application class because only it manages swap chains, but all my attempts to use viewport failed.

Is my goal even possible?

I would really appreciate a code sample or at least some directions where I would be able to find a solution.
Thanks

**Comment by PandrPi** [comment]
It's been almost a month since I've opened this issue. Could someone please look at it and give feedback?

**Comment by Sergio0694** [comment]
> "However, I'm stuck at the stage where I need to render the texture not for the entire window but only within a little rect of the window, so that both the title bar and the texture rendering will actually work."

There are several ways to do this, and it really just depends on your setup. If you just want the default title bar, you should probably be able to do that by tweaking the parameters passed to the various `CreateWindowExW` etc. methods used in `Win32ApplicationRunner`. I'm not really too familiar with classic Win32 windowing, so not sure off the top of my head how to get the standard title bar back, you'll have to do a minimum of research (unless perhaps @rickbrew wanted to chime in on that).

> "It's been almost a month since I've opened this issue. Could someone please look at it and give feedback?"

Please remember that this is an open source project, that me and other contributors are working on entirely for free and on their free time. There is no supporting license nor SLA agreements or anything. We're all just replying when we can 🙂
