### ISSUE TITLE
Concurrent GPU access

### ISSUE THREAD

**Issue by miyconst** [Sergio0694/ComputeSharp#62]
Hi @Sergio0694!

I am trying to utilize a GPU for report building in my system, but when two users request a report at the same time, GPU access fails with the following error:

```
System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
```

Is this expected? Does this mean that any instance of `ComputeSharp.GraphicsDevice` can be used from only one thread at a given moment of time?

Here is a simple reproduction scenario:

```cs
public void GpuMultiThread()
{
    int count = 10;
    List<Task> tasks = new List<Task>();

    for (int i = 0; i < count; i++)
    {
        int index = i;

        tasks.Add(Task.Run(() =>
        {
            ReadWriteBuffer<int> buffer = Gpu.Default.AllocateReadWriteBuffer<int>(count);

            Gpu.Default.For(count, thread =>
            {
                buffer[thread.X] = thread.X;
            });

            int sum = buffer.GetData().Sum();

            this.TestOutput.WriteLine($"Thread: {index}, sum: {sum}.");
        }));
    }

    Task.WhenAll(tasks).GetAwaiter().GetResult();
}
```

```
  Message: 
    System.ArgumentException : An item with the same key has already been added. Key: (39086322, 32, 1, 1)
  Stack Trace: 
    Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    ShaderRunner.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, Int32 threadsX, Int32 threadsY, Int32 threadsZ, Action`1 action)
    ShaderRunner.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, Action`1 action)
    GraphicsDeviceExtensions.For(GraphicsDevice device, Int32 x, Action`1 action)
```

**Comment by miyconst** [comment]
After updating to `1.3.0` I see the following exception instead:

```
Message: 
    ComputeSharp.Exceptions.GraphicsDeviceMismatchException : Invalid pairing of graphics devices used to run a compute shader and allocate memory buffers.
    The graphics devices used to allocate buffers and run the shader must be the same instance, not just be using the same physical device.
    You can still run different shaders on different devices, but a shader run on one device must only use buffers allocated by the same device instance.
    
  Stack Trace: 
    CommandList.SetComputeRootDescriptorTable(Int32 rootParameterIndex, GraphicsResource resource)
    ShaderRunner.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, Int32 threadsX, Int32 threadsY, Int32 threadsZ, Action`1 action)
    ShaderRunner.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, Action`1 action)
    GraphicsDeviceExtensions.For(GraphicsDevice device, Int32 x, Action`1 action)
```

Which makes me think, that the `Gpu.Default` property is not always returning the same GPU.

**But**, if I update the code sample to:

```cs
public void GpuMultiThread()
{
    int count = 10;
    List<Task> tasks = new List<Task>();
    GraphicsDevice gpu = Gpu.Default;

    for (int i = 0; i < count; i++)
    {
        int index = i;

        tasks.Add(Task.Run(() =>
        {
            ReadWriteBuffer<int> buffer = gpu.AllocateReadWriteBuffer<int>(count);

            gpu.For(count, thread =>
            {
                buffer[thread.X] = thread.X;
            });

            int sum = buffer.GetData().Sum();

            this.TestOutput.WriteLine($"Thread: {index}, sum: {sum}.");
        }));
    }

    Task.WhenAll(tasks).GetAwaiter().GetResult();
}
```

Then it hangs on something and never completes.

**Comment by Sergio0694** [comment]
Hey @miyconst - so, the `Gpu.Default` property always returns the same instance, _but_ since the class is not thread-safe per se (by that I mean, the `Default` property is initialized in the static constructor, which is not thread safe), you might end up with different GPU instances if two threads are accessing the `Default` property at the same time.

As for the hang, I'm not really sure about that, will try to see if I can replicate that on my end!

**Comment by miyconst** [comment]
@Sergio0694 thanks for looking into it!

>As for the hang, I'm not really sure about that, will try to see if I can replicate that on my end!

Do you mean that my code snippet work for you with no issues?

**Comment by Sergio0694** [comment]
I meant to say that I'll try to replicate that on my end, as I haven't had time to do that just yet.

**Comment by JimBobSquarePants** [comment]
>Default property is initialized in the static constructor, which is not thread safe), you might end up with different GPU instances if two threads are accessing the Default property at the same time.

`Lazy<T>`?

**Comment by Sergio0694** [comment]
@JimBobSquarePants That should actually be perfect for this situation, I hadn't thought about that class! I'll give it a try, thanks for the suggestion! 😄

**Comment by Sergio0694** [comment]
Hey @miyconst - sorry for the delay, I finally have an update on this 😅

So, couple of things:
1) Turns out static constructors in C# are in fact thread-safe (see [here](https://github.com/dotnet/docs/issues/10243#issuecomment-467222385), cc. @JimBobSquarePants FYI).
2. I'm doing a major refactoring of the whole library, moving away from lambda expressions to generic structs (similar to the value delegate approach we use in `ImageSharp`), which makes life a lot easier for the reflection system that creates the GPU shaders. In that branch, I've also made a fix for the concurrent accesses to the `Gpu.Default` property ([here](e2ccda0144db28a5fa4155fe22a29524d03ed98b)) - that property is now loaded directly from the static constructor, which should make it perfectly safe for concurrent access at any time. If you try that branch out (or just wait for the updated NuGet packages), let me know how it goes!

**Comment by miyconst** [comment]
Thank you @Sergio0694 for not letting the library stagnate.

**Comment by Sergio0694** [comment]
No worries, I still have quite a few updates planned for this, including using the new code generators to replace the decompiler currently used to retrieve the shader code. Not abandoning this library any time soo, it's just not my main project so I can't dedicate much time on it every day 😄

**Comment by Sergio0694** [comment]
Hey @miyconst - I've just published version `1.4.0` of `ComputeSharp` which also includes a fix for this issue.
Try it out and let me know if it works for you! 😊

**Comment by miyconst** [comment]
Hello @Sergio0694 and thank you for not abandoning the project. For now my focus has shifted to another subject and I am not sure when I will be able to test the new release, but I will keep you posted if I find a minute to do so.

Feel free to close the issue if it's fixed.

**Comment by Sergio0694** [comment]
No problem, just wanted to ping you to confirm I had addressed this in the new release! 😊
Take care, and feel free to ping me again should you use the library in the future!
