### ISSUE TITLE
[question] performance slower than CPU, am I using this library wrong way?

### ISSUE THREAD

**Issue by JohnMasen** [Sergio0694/ComputeSharp#66]
Hi,
I'm porting my CPU based application to GPU. in order to find out the right library, I'm comparing several GPU accelerated libraries. it turns out ComputeSharp is slower than CPU which I think I'm not using this library correctly. 
I've tried to read the document and source code carefully, however all samples and documents shows just 1-time GPU call, not in a loop which my application does.
could you please help check if I did any thing wrong in the library usage?
Thanks in advise.

source code : https://github.com/JohnMasen/VirusSimulator
project: ComputeShaderTest.csproj

output from my Surface Book 2
------------------------
PS D:\GithubRoot\VirusSimulator\src\ComputeShaderTest\bin\Release\netcoreapp3.1\publish> .\ComputeShaderTest.exe 100000 1 true
Test with 100000 items, duration =00:00:01,copy back =True
Testing with CPU 1814
Testing with ComputeSharp [Intel(R) UHD Graphics 620] 353
Testing with ComputeSharp [NVIDIA GeForce GTX 1050] 595
...
PS D:\GithubRoot\VirusSimulator\src\ComputeShaderTest\bin\Release\netcoreapp3.1\publish> .\ComputeShaderTest.exe 100000 1 false
Test with 100000 items, duration =00:00:01,copy back =False
Testing with CPU 2156
Testing with ComputeSharp [Intel(R) UHD Graphics 620] 699
Testing with ComputeSharp [NVIDIA GeForce GTX 1050] 2030
...

**Comment by JohnMasen** [comment]
I found out this issue is cause by shader commands too simple(1 line of code only).

**Comment by Sergio0694** [comment]
Hi John, thank you for your interest in my library!
Yeah if the shader code is too simple (eg. just assigning a value to a buffer location), the overhead of the actual shader invocation can result in the GPU code being slower.

You can see the real advantage of GPU computation with more complex compute shaders, eg. the ones in the custom bokeh blur and gaussian blur image processors you can find in one of the sample projects in the repository.

When running those, I'm getting over 13x speed improvements on my PC, with a Ryzen 2700X and a GTX1080.

Hope that helps!

**Comment by JohnMasen** [comment]
You're right, looks I have a lot to learn in GPU programming.
