### ISSUE TITLE
GraphicsDevice.EnumerateDevices() yields the same dGPU twice (but with different LUID) when RDP'd in

### ISSUE THREAD

**Issue by matthew-a-thomas** [Sergio0694/ComputeSharp#688]
### Reproduction Steps

First, remote into the PC.

Second, execute the following code:

.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="ComputeSharp" Version="3.0.0-preview1" />
    </ItemGroup>
</Project>
```

Program.cs
```csharp
using System;
using ComputeSharp;
foreach (var graphicsDevice in GraphicsDevice.EnumerateDevices())
{
    using (graphicsDevice)
    {
        Console.WriteLine($"{graphicsDevice.Name} ({graphicsDevice.Luid})");
    }
}
```

Output when remoted in:
> NVIDIA T400 4GB (172697)
> Intel(R) UHD Graphics 770 (175730)
> NVIDIA T400 4GB (414755280)
> Microsoft Basic Render Driver (175685)

Notice the output repeats the NVIDIA dGPU. Only one NVIDIA card is physically installed, and only one NVIDIA device is listed in the output when I'm directly logged into the PC.

### Expected Behavior

I expect the RDP session should not cause graphics devices to be repeated.

### Actual Behavior

One of the graphics devices is repeated when logged in through RDP.

### System info

ComputeSharp 3.0.0-preview1

Processor	12th Gen Intel(R) Core(TM) i5-12600K   3.70 GHz
Installed RAM	32.0 GB (31.7 GB usable)

Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎9/‎29/‎2022
OS build	22631.2715
Experience	Windows Feature Experience Pack 1000.22677.1000.0

[DxDiag.txt](https://github.com/Sergio0694/ComputeSharp/files/13477395/DxDiag.txt)

```
dotnet --version
8.0.100
```

**Comment by Sergio0694** [comment]
I've asked the DirectX team, this is apparently the expected behavior in RDP scenarios, and like @rickbrew said I'm just forwarding whatever `IDXGIFactory6` gives me when enumerative adapters. I'll just add some remarks to that API to explicitly call out the behavior in this case 🙂

**Comment by matthew-a-thomas** [comment]
> you should be able to filter out adapters with LUIDs you've already seen before

@rickbrew If those are the same LUIDs as are included in the OP output then the LUIDs are not duplicated.

**Comment by matthew-a-thomas** [comment]
@Sergio0694 Do you have any recommendations for filtering them out? The use case I have in mind is distributing computation across all available resources. But that's difficult to accomplish if I can't tell the difference between a "real" graphics card and a "fake" one. I can filter out duplicate _names_ but then what about systems with multiple "real" graphics devices having the same name?
