### ISSUE TITLE
Possibility of cross-platform support using Vulkan?

### ISSUE THREAD

**Issue by chilipepperhott** [Sergio0694/ComputeSharp#70]
I do not know much about the internal workings of ComputeSharp to say how possible it is, but what is the feasability of adding cross platform support using Vulkan, as Vulkan has first class HLSL support?

**Comment by Sergio0694** [comment]
Hey, sorry for the delay!
Unfortunately I don't plan to add support for Vulkan - right now the library just heavily relies on `Vortice.Windows` for the DirectX bindings and isn't really built with cross-platform in mind. Also I should add the library itself was supposed to be smaller in scope and just a tool to easily write/run compute shaders on Windows, I didn't plan to expand it too much beyond that, given that unfortunately this is just a side project for me and time is limited 😅

Appreciate the interest in `ComputeSharp` though!
Will close this for now as I'm likely not going to work on this any time soon.
