### ISSUE TITLE
Is .NET Community Toolkit alive? What is its status?

### ISSUE THREAD

**Issue by AlexRadch** [Sergio0694/ComputeSharp#759]
Is [.NET Community Toolkit](https://github.com/CommunityToolkit/dotnet) alive? What is its status?

**Comment by Sergio0694** [comment]
Of course it's alive 🙂
The status is that it's fully supported, and we have several planned features for future releases.

Also, this is clearly the wrong repo, not really sure why you posted this issue here.

**Comment by AlexRadch** [comment]
I wrote here because there has been silence there for several months now. There are a lot of unanswered questions, pull requests, etc. And there the last merge was 3 months ago.

**Comment by AlexRadch** [comment]
I have a desire to help develop and write code, participate in discussions, but there is silence there and I don’t understand how I can participate in development there if no one communicates...
