### ISSUE TITLE
Is .netframework 4.8 support?

### ISSUE THREAD

**Issue by yh0908** [Sergio0694/ComputeSharp#760]
Not Support Netframwork 4.8 ?

Downloaded from Nugget, but IComputeShader is not available

**Comment by Sergio0694** [comment]
ComputeSharp supports .NET Framework 4.8 via .NET Standard 2.0, available in ComputeSharp 2.1.
See: https://www.nuget.org/packages/ComputeSharp/2.1.0#supportedframeworks-body-tab.
