### ISSUE TITLE
'GeneratedComputeShaderDescriptorAttribute' did not add IComputeShaderDescriptor

### ISSUE THREAD

**Issue by 3DartBlade** [Sergio0694/ComputeSharp#790]
### Description

I've been trying to get the sample 'MultiplyByTwo' code running from the wiki. I finally figured out after a lot of searching that I need the 3.0.0 preview version of the package, and my project is now using .NET 8.0 thanks to primary constructors.

However, calling `GraphicsDevice.Run` exactly as it is on the wiki, with a struck exactly as on the wiki (see code below), causes this compilation error: `CS0315	The type 'MultiplyByTwo' cannot be used as type parameter 'T' in the generic type or method 'GraphicsDeviceExtensions.For<T>(GraphicsDevice, int, in T)'. There is no boxing conversion from 'MultiplyByTwo' to 'ComputeSharp.Descriptors.IComputeShaderDescriptor<MultiplyByTwo>'.`

Through the internet and the description of the `GeneratedComputeShaderDescriptorAttribute` I found out that this is probably due to the `GraphicsDevice.Run` method expecting a T where T has an `IComputeShaderDescriptor` which apparently my struct doesn't have despite the `GeneratedComputeShaderDescriptorAttribute` specified above it.

### Reproduction Steps

1. Start a new project in Microsoft Visual Studio Community 2022 Version 17.9.6
    - Console App, Place solution and project in the same directory, Framework: .NET 8.0 (Long Term Support), Do not use top-level statements
3. Install ComputeSharp 3.0.0 through VS's NuGet manager GUI
4. Use the code specified on the wiki: 
``` C#
using System;
using System.Linq;
using ComputeSharp;

public class Program
{
    public static void Main(string[] args)
    {
        int[] array = [.. Enumerable.Range(1, 100)];

        // Allocate a GPU buffer and copy the data to it.
        // We want the shader to modify the items in-place, so we
        // can allocate a single read-write buffer to work on.
        using ReadWriteBuffer<int> buffer = GraphicsDevice.GetDefault().AllocateReadWriteBuffer(array);

        GraphicsDevice.GetDefault().For(buffer.Length, new MultiplyByTwo(buffer));

        // Get the data back
        buffer.CopyTo(array);
    }
}

[ThreadGroupSize(DefaultThreadGroupSizes.X)]
[GeneratedComputeShaderDescriptor]
public readonly partial struct MultiplyByTwo(ReadWriteBuffer<int> buffer) : IComputeShader
{
    public void Execute()
    {
        buffer[ThreadIds.X] *= 2;
    }
}
```

### Expected Behavior

The script compiles with no error.

### Actual Behavior

Doesn't compile and spits out the above mentioned error code.

### System info

- Windows 11
- Microsoft Visual Studio Community 2022 Version 17.9.6
- ComputeSharp 3.0.0-preview2

If you need any additional information or testing, don't hesitate to reach out!

**Comment by 3DartBlade** [comment]
Project files:
[ComputeSharpTest3.zip](https://github.com/Sergio0694/ComputeSharp/files/15148648/ComputeSharpTest3.zip)
(Ignore the typo, I've been trying to get this to work for a long time now)

**Comment by Sergio0694** [comment]
You're missing `AllowUnsafeBlocks`, the analyzers are telling you that as well 🙂

![image](https://github.com/Sergio0694/ComputeSharp/assets/10199417/c633f295-adcd-4874-be55-9f8e92de21f7)

Just set that in your .csproj and it'll work as expected. The generators are disabled otherwise.

**Comment by 3DartBlade** [comment]
Thank you, that solved it!

For some reason it did not show me those errors, but that's probably _my_ Visual Studio's fault. At least if someone has the same issue they'll find the answer here. I'm just glad it works now!

**Comment by atonalfreerider** [comment]
This may be beyond the scope of this project, but I'm trying to run on Linux. The same error is appearing:

```
CS0315	The type 'MultiplyByTwo' cannot be used as type parameter 'T' in the generic type or method 'GraphicsDeviceExtensions.For<T>(GraphicsDevice, int, in T)'. There is no boxing conversion from 'MultiplyByTwo' to 'ComputeSharp.Descriptors.IComputeShaderDescriptor<MultiplyByTwo>'.
```

the _partial_ keyword is greyed out for the struct

I have `AllowUnsafeBlocks` enabled

Ubuntu 24
.NET 9.0
ComputeSharp 3.1.0
