### ISSUE TITLE
Minor errors in the sample code

### ISSUE THREAD

**Issue by imgits** [Sergio0694/ComputeSharp#820]
The code in file **ComputeSharp/samples/ComputeSharp.Benchmark/Blas/BlasHelpers.cs** at line 97:

`int x_offset = (ThreadIds.X * n * p) + (ThreadIds.Y * m);`

Should it be:

`int x_offset = (ThreadIds.X * n * m) + (ThreadIds.Y * m);`

That is, change '**_p_**' to '_**m**_'

**Comment by Sergio0694** [comment]
Fixed, thank you! 🙂
