### ISSUE TITLE
This not working for .NET 9

### ISSUE THREAD

**Issue by RoccoZero** [Sergio0694/ComputeSharp#833]
This not working for .NET 9

**Comment by Sergio0694** [comment]
This is not actionable. Can you include more info? What is not working? Works fine for me on .NET 9, so closing for now.

**Comment by RoccoZero** [comment]
Sorry for not writing details 
 I can't install NuGet packages, it just says it doesn't support .NET9

**Comment by Sergio0694** [comment]
Which package are you trying to install? What's your TFM in your project?

**Comment by RoccoZero** [comment]
TFM dotnet 9
![image](https://github.com/user-attachments/assets/9dfedff3-8881-4ea3-8f2b-81d7451e7977)

**Comment by RoccoZero** [comment]
problem solved, sorry to bother you
