### ISSUE TITLE
Shader compilation failed when implementing IComputeShader interface in a different way.

### ISSUE THREAD

**Issue by HoneyFox** [Sergio0694/ComputeSharp#855]
### Reproduction Steps

When writing a compute shader, use `void IComputeShader.Execute()` instead of `public void Execute()`.

### Expected Behavior

The shader should be compiled normally as if `public void Execute()` is used.

### Actual Behavior

The compute shader cannot be compiled. Error reports as follows: 

> "The DXC compiler encountered one or more errors while trying to compile the shader: "error: expected external declaration [NumThreads(__GroupSize__get_X, __GroupSize__get_Y, __GroupSize__get_Z)] .". Make sure to only be using supported features by checking the README file in the ComputeSharp repository: https://github.com/Sergio0694/ComputeSharp. If you're sure that your C# shader code is valid, please open an issue an include a working repro and this error message."

### System info

ComputeSharp 3.0.1
Windows 10
Visual Studio 2022 17.11.4, .NET 8.0

**Comment by HoneyFox** [comment]
It's not really a serious issue after all...

**Comment by Sergio0694** [comment]
Ah, yeah agreed it'd be nice to support this scenario too, thank you for opening this! 🙂
