### ISSUE TITLE
This is exactly what I was looking for!

### ISSUE THREAD

**Issue by zamuya** [Sergio0694/ComputeSharp#94]
I was looking at the code, and I've been trying to figure out how to make my server run on a GPU that can be powerful enough to handle their speedy browsing while making sure their session is completely encrypted. I needed to have my server on a GPU, but CUDA wasn't going to cut. I have read nearly every page that NVIDIA has to offer. 

All I did was do a search because I gave up. I was thought. This is dumb. So I typed in. Int4 Uint3 int static float tensor. And then a reddit post of yours popped up. 

So it got me excited because you reroute this traffic to CUDA? Or do you go directly to Tensor? If not, I know of software that will convert CUDA related functions to be compatible with tensor. It's not really a production solution, but I am always willing to push the edge. It's not like my website is super important or anything. It doesn't have transactions or really any personal info. I just want to make sure privacy is kept. My servers are with Oracle so they take really good care of all of the security that goes in and out. 

If this works out and it speeds up my instance. I would like to pay you here and there for tweaks, and further developments. Plus, you will get to see what your software can do on 8 NVIDIA A100 GPU 40GB / 2040GB DDR4 / 4tB NVMe / 128 Core Processor / and 50gbps internet connection. 

But given your background, I'm sure you already have access to one. 

I do have a list here of random functions and the exact syntax that I will need. Let me know which ones are supported and if it'll be a problem 

int 

uint32_t

uint2

uint64_t

dim3

tex1Dfetch as float4 and int4

fnv4

uint4

shfl

uint8_t

uint256

uint16_t

int

ptarget / HLSL

FFT8

FFT16

FFT32

FFT256

u8 / u16 / u32 / 64

Can it handle a generation like this? This isn't any real code. Just various random code that is like the original. 

 uint32_t abx = (t  >> 4) * 24U ^ ((ab^t)  << 2);
 // uint2x4

 #pragma generate A
		for (int i = 0; i < 16; i += 4)
		{
			W[i] ^= W[28 + i] ^ 256;
			W[i + 1] ^= W[28 + i + 1];
			W[i + 5] ^= W[28 + i + 5];
			W[i + 9] ^= W[28 + i + 9];
		}

**Comment by Sergio0694** [comment]
Hey, thank you for your support, glad to hear you like the library so far! 😄
It's always interesting to hear from other devs trying it out, and I love seeing this project being adopted in all kinds of scenarios.

> "So it got me excited because you reroute this traffic to CUDA? Or do you go directly to Tensor? "

Nope, there is no CUDA at all actually 🙂
This library only uses DirectX 12 compute shaders, which means unlike CUDA it only runs on Windows or Linux on WSL, but it can run on all kinds of GPU devices (nvidia, AMD, Intel, etc.). It doesn't use any proprietary tech, it's all self-contained on top of DX12.
The way this works is that C# code defining a shader is rewritten into HLSL, then compiled at runtime and dispatched on the GPU.

> "But given your background, I'm sure you already have access to one."

Ahah not really, just working on this project as a hobby on my home desktop, I have a measly GTX1080 here 😉

> "I do have a list here of random functions and the exact syntax that I will need. Let me know which ones are supported and if it'll be a problem"

As I mentioned, the library transpiles C# code to HLSL, so the goal is to support everything that can run on an HLSL DX12 compute shader with the SM6.0 profile. Right now I support a decent number of features already (including group shared buffer), and pretty much all the compute shader HLSL intrinsics. For more info on HLSL, you can read [the docs here](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl).

I still need to write updated docs/wiki for the new 2.0 rewrite of the library, but in general (for now), you can use most scalar and vector HLSL types ([docs here](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-data-types)), and all the various resource types (buffers, textures, etc.) that you see included in the library itself. You'll also find a complete list of all the supported HLSL intrinsics in the `Hlsl` class, which can be used from compute shaders and will be rewritten to the corresponding intrinsics in the actual shader that is run on the GPU.

> **NOTE:** if you're not doing this already, I **strongly** recommend you to only look at the code from the `dev` branch, as I'm basically rewriting the entire library from scratch. The code in the `master` branch is outdated now and no longer reflects the current status of the library. Same for the current NuGet package, that's outdated as well. I'll be publishing a new preview package with the updated codebase soon, just waiting to fix a few more things first.

> "Can it handle a generation like this? This isn't any real code. Just various random code that is like the original."

Sure! That's just normal bit trickery on some `uint` values, that'll work just fine in a compute shader 👍

**Comment by zamuya** [comment]
That is very impressive! Is there I way I could compile this into a package? Or is this something I would have to install seperately on each system? Have you tried it on Hyper-V yet? And as for the hardware. I know that it's powerful. I know that it can do some things, but when it comes to actually figuring out what calls what in code and writing a library for it. I just a few days doing nothing being reading, trying to make diagrams to make sense of how tensor cores work. I have the concept, I get the matrix, it makes sense, but at the same time.... what? Lol, how does it not throw off at least 70% of errors when you have to compile your calculation like a rubix cube?

**Comment by zamuya** [comment]
Wait HOLD THE PHONE. 2MB? I was expecting like a 700MB library to clutter my storage forever haha. 2MB is like a PHP extension add-on and that's the most impressive thing yet!!

**Comment by Sergio0694** [comment]
> Is there I way I could compile this into a package? Or is this something I would have to install seperately on each system?

Once I get to upload a preview package for the new version, you'll just need to reference ComputeSharp from NuGet as you would do for any other library, and then NuGet will just handle everything for you when building your app/library 😄
If you want to try out a local build, you can grab a preview package from the CI artifacts:
- Open the [GitHub Actions](https://github.com/Sergio0694/ComputeSharp/actions) tab
- Pick any successful run from the `dev` branch
- Scroll down to "Artifacts" and download `ComputeSharp.nupkg`
- Extract the `.nupkg` file into a local NuGet feed for your library, which you can setup however you want (eg. with a local `nuget.config` file or from Visual Studio's settings)
- Then just install it into your library and you're good to go.

Of course, I'd recommend waiting for a NuGet package before actually distributing your app, as it'll make bundling all the necessary dependencies much easier, as NuGet will do that for you. The package is just 9MB in total, it's relatively small, yeah 🙂

> "Have you tried it on Hyper-V yet?"

I have not, I've only tried this on my desktop and notebook, and of course also in the CI, which runs on some Windows Server 2019 VM. If you want performance though of course you'll want to make sure a dedicated GPU is available to use. ComputeSharp does support the [WARP device](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp) as a software fallback if no GPU is available, but of course it's much much slower than an actual GPU.

> "how tensor cores work"

Note that at least for now, you cannot directly use tensor cores with ComputeSharp, as they're not exposed directly to compute shaders. I might look into that in the future with some integration with DirectML, but for now they're not supported yet.

**Comment by zamuya** [comment]
Wow. One more time. Fantastic job. I tried to put it through a few code testers designed to find even the slightest mistakes, and they didn't find any. I have a side project that I'm doing because I wanted to get into it. I need 3 scripts modified to perform at high efficiencies. I need an algorithm created that pays out people at certain intervals and events. The code is based already on an open-source project. The code looks pretty refined. And I could probably use help with a parser. And then maybe you could develop this a little more while you work on those. I would say you would spend 4 hours on the scripts, 4 hours on the algorithm, and 8 hours on the parser, and whatever else if you wanted to tweak your software. How does $450 sound? And if you want to help a bit more with these with me, I'll give you 10% of the revenue if you can start working on the tensor core thing as much as you can. It's not a huge project which is what's nice about it, but there were some things that bothered me in the market. Very dishonest people and I want to steer that away from it. The small venture generates about $180 per day for me. It doesn't cover my expenses, but I will of course give you the 10% of revenue from all aspects of this project. Add me on Skype. @andylehti

**Comment by zamuya** [comment]
Actually, wait, don't. I installed something and it now blocks the port from skype to the internet, but the firewall isn't the problem and reinstalling skype didn't do anything ha! If you're willing to talk a bit. I'll make a new team on Microsoft Teams.

**Comment by Sergio0694** [comment]
> "tensor core thing"

Just FYI, do keep in mind that [Tensor Cores](https://arxiv.org/pdf/1803.04014.pdf) are not really general purpose compute units - they're just meant to be used to accelerate fused multiply-accumulate operations. As such, they're leveraged to accelerate deep learning models, since FMA operations are at the heart of many operations there (eg. fully connected layers, convolutions, etc.). Unless you actually need to run code that specifically relies on many FMA operations, Tensor Cores aren't really useful. I'm not saying they're bad, but they only make sense in very specific scenarios, it's not like they can run arbitrary code "faster".

I'm really glad you like this library, and I really appreciate you supporting my work and hope you will continue to do so in the future, but unfortunately I'm not able to start working on yet another project at this time. I'm going to close this issue for now, but you can definitely try out ComputeSharp in your application and I hope it helps you with what you're trying to do. Of course you're welcome to open issues if you find a specific bug or if you have a specific feature idea. Though I can't guarantee I'll be able to implement all of those, I'll still triage and look into all the new issues and provide feedback if necessary 🙂
